// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file jon_shared_cmd_cv.proto (package cmd.CV, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "./buf/validate/validate_pb";
import type { JonGuiDataVideoChannel } from "./jon_shared_data_types_pb";
import { file_jon_shared_data_types } from "./jon_shared_data_types_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file jon_shared_cmd_cv.proto.
 */
export const file_jon_shared_cmd_cv: GenFile = /*@__PURE__*/
  fileDesc("Chdqb25fc2hhcmVkX2NtZF9jdi5wcm90bxIGY21kLkNWIoIGCgRSb290Ei4KDnNldF9hdXRvX2ZvY3VzGAEgASgLMhQuY21kLkNWLlNldEF1dG9Gb2N1c0gAEjAKD3N0YXJ0X3RyYWNrX25kYxgCIAEoCzIVLmNtZC5DVi5TdGFydFRyYWNrTkRDSAASJwoKc3RvcF90cmFjaxgDIAEoCzIRLmNtZC5DVi5TdG9wVHJhY2tIABI4ChN2YW1waXJlX21vZGVfZW5hYmxlGAQgASgLMhkuY21kLkNWLlZhbXBpcmVNb2RlRW5hYmxlSAASOgoUdmFtcGlyZV9tb2RlX2Rpc2FibGUYBSABKAsyGi5jbWQuQ1YuVmFtcGlyZU1vZGVEaXNhYmxlSAASRAoZc3RhYmlsaXphdGlvbl9tb2RlX2VuYWJsZRgGIAEoCzIfLmNtZC5DVi5TdGFiaWxpemF0aW9uTW9kZUVuYWJsZUgAEkYKGnN0YWJpbGl6YXRpb25fbW9kZV9kaXNhYmxlGAcgASgLMiAuY21kLkNWLlN0YWJpbGl6YXRpb25Nb2RlRGlzYWJsZUgAEicKCmR1bXBfc3RhcnQYCCABKAsyES5jbWQuQ1YuRHVtcFN0YXJ0SAASJQoJZHVtcF9zdG9wGAkgASgLMhAuY21kLkNWLkR1bXBTdG9wSAASQAoXcmVjb2duaXRpb25fbW9kZV9lbmFibGUYCiABKAsyHS5jbWQuQ1YuUmVjb2duaXRpb25Nb2RlRW5hYmxlSAASQgoYcmVjb2duaXRpb25fbW9kZV9kaXNhYmxlGAsgASgLMh4uY21kLkNWLlJlY29nbml0aW9uTW9kZURpc2FibGVIABIrCgxicmlkZ2Vfc3RhcnQYFCABKAsyEy5jbWQuQ1YuQnJpZGdlU3RhcnRIABIpCgticmlkZ2Vfc3RvcBgVIAEoCzISLmNtZC5DVi5CcmlkZ2VTdG9wSAASLwoOYnJpZGdlX3Jlc3RhcnQYFiABKAsyFS5jbWQuQ1YuQnJpZGdlUmVzdGFydEgAQgwKA2NtZBIFukgCCAEiEwoRVmFtcGlyZU1vZGVFbmFibGUiCwoJRHVtcFN0YXJ0IgoKCER1bXBTdG9wIhQKElZhbXBpcmVNb2RlRGlzYWJsZSIZChdTdGFiaWxpemF0aW9uTW9kZUVuYWJsZSIaChhTdGFiaWxpemF0aW9uTW9kZURpc2FibGUiFwoVUmVjb2duaXRpb25Nb2RlRW5hYmxlIhgKFlJlY29nbml0aW9uTW9kZURpc2FibGUiVwoMU2V0QXV0b0ZvY3VzEjgKB2NoYW5uZWwYASABKA4yGy5zZXIuSm9uR3VpRGF0YVZpZGVvQ2hhbm5lbEIKukgHggEEEAEgABINCgV2YWx1ZRgCIAEoCCK5AQoNU3RhcnRUcmFja05EQxI4CgdjaGFubmVsGAEgASgOMhsuc2VyLkpvbkd1aURhdGFWaWRlb0NoYW5uZWxCCrpIB4IBBBABIAASIgoBeBgCIAEoAUIXukgUEhIZAAAAAAAA8D8pAAAAAAAA8L8SIgoBeRgDIAEoAUIXukgUEhIZAAAAAAAA8D8pAAAAAAAA8L8SEgoKZnJhbWVfdGltZRgEIAEoBBISCgpzdGF0ZV90aW1lGAUgASgEIgsKCVN0b3BUcmFjayINCgtCcmlkZ2VTdGFydCIbCgpCcmlkZ2VTdG9wEg0KBWZvcmNlGAEgASgIIh4KDUJyaWRnZVJlc3RhcnQSDQoFZm9yY2UYASABKAhCSVpHZ2l0LWNvZGVjb21taXQuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb20vdjEvcmVwb3MvamV0dGlzb24vam9ucC9jbWQvY3ZiBnByb3RvMw", [file_buf_validate_validate, file_jon_shared_data_types]);

/**
 * @generated from message cmd.CV.Root
 */
export type Root = Message<"cmd.CV.Root"> & {
  /**
   * @generated from oneof cmd.CV.Root.cmd
   */
  cmd: {
    /**
     * @generated from field: cmd.CV.SetAutoFocus set_auto_focus = 1;
     */
    value: SetAutoFocus;
    case: "setAutoFocus";
  } | {
    /**
     * @generated from field: cmd.CV.StartTrackNDC start_track_ndc = 2;
     */
    value: StartTrackNDC;
    case: "startTrackNdc";
  } | {
    /**
     * @generated from field: cmd.CV.StopTrack stop_track = 3;
     */
    value: StopTrack;
    case: "stopTrack";
  } | {
    /**
     * @generated from field: cmd.CV.VampireModeEnable vampire_mode_enable = 4;
     */
    value: VampireModeEnable;
    case: "vampireModeEnable";
  } | {
    /**
     * @generated from field: cmd.CV.VampireModeDisable vampire_mode_disable = 5;
     */
    value: VampireModeDisable;
    case: "vampireModeDisable";
  } | {
    /**
     * @generated from field: cmd.CV.StabilizationModeEnable stabilization_mode_enable = 6;
     */
    value: StabilizationModeEnable;
    case: "stabilizationModeEnable";
  } | {
    /**
     * @generated from field: cmd.CV.StabilizationModeDisable stabilization_mode_disable = 7;
     */
    value: StabilizationModeDisable;
    case: "stabilizationModeDisable";
  } | {
    /**
     * @generated from field: cmd.CV.DumpStart dump_start = 8;
     */
    value: DumpStart;
    case: "dumpStart";
  } | {
    /**
     * @generated from field: cmd.CV.DumpStop dump_stop = 9;
     */
    value: DumpStop;
    case: "dumpStop";
  } | {
    /**
     * @generated from field: cmd.CV.RecognitionModeEnable recognition_mode_enable = 10;
     */
    value: RecognitionModeEnable;
    case: "recognitionModeEnable";
  } | {
    /**
     * @generated from field: cmd.CV.RecognitionModeDisable recognition_mode_disable = 11;
     */
    value: RecognitionModeDisable;
    case: "recognitionModeDisable";
  } | {
    /**
     * CV Bridge container control
     *
     * @generated from field: cmd.CV.BridgeStart bridge_start = 20;
     */
    value: BridgeStart;
    case: "bridgeStart";
  } | {
    /**
     * @generated from field: cmd.CV.BridgeStop bridge_stop = 21;
     */
    value: BridgeStop;
    case: "bridgeStop";
  } | {
    /**
     * @generated from field: cmd.CV.BridgeRestart bridge_restart = 22;
     */
    value: BridgeRestart;
    case: "bridgeRestart";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message cmd.CV.Root.
 * Use `create(RootSchema)` to create a new message.
 */
export const RootSchema: GenMessage<Root> = /*@__PURE__*/
  messageDesc(file_jon_shared_cmd_cv, 0);

/**
 * @generated from message cmd.CV.VampireModeEnable
 */
export type VampireModeEnable = Message<"cmd.CV.VampireModeEnable"> & {
};

/**
 * Describes the message cmd.CV.VampireModeEnable.
 * Use `create(VampireModeEnableSchema)` to create a new message.
 */
export const VampireModeEnableSchema: GenMessage<VampireModeEnable> = /*@__PURE__*/
  messageDesc(file_jon_shared_cmd_cv, 1);

/**
 * @generated from message cmd.CV.DumpStart
 */
export type DumpStart = Message<"cmd.CV.DumpStart"> & {
};

/**
 * Describes the message cmd.CV.DumpStart.
 * Use `create(DumpStartSchema)` to create a new message.
 */
export const DumpStartSchema: GenMessage<DumpStart> = /*@__PURE__*/
  messageDesc(file_jon_shared_cmd_cv, 2);

/**
 * @generated from message cmd.CV.DumpStop
 */
export type DumpStop = Message<"cmd.CV.DumpStop"> & {
};

/**
 * Describes the message cmd.CV.DumpStop.
 * Use `create(DumpStopSchema)` to create a new message.
 */
export const DumpStopSchema: GenMessage<DumpStop> = /*@__PURE__*/
  messageDesc(file_jon_shared_cmd_cv, 3);

/**
 * @generated from message cmd.CV.VampireModeDisable
 */
export type VampireModeDisable = Message<"cmd.CV.VampireModeDisable"> & {
};

/**
 * Describes the message cmd.CV.VampireModeDisable.
 * Use `create(VampireModeDisableSchema)` to create a new message.
 */
export const VampireModeDisableSchema: GenMessage<VampireModeDisable> = /*@__PURE__*/
  messageDesc(file_jon_shared_cmd_cv, 4);

/**
 * @generated from message cmd.CV.StabilizationModeEnable
 */
export type StabilizationModeEnable = Message<"cmd.CV.StabilizationModeEnable"> & {
};

/**
 * Describes the message cmd.CV.StabilizationModeEnable.
 * Use `create(StabilizationModeEnableSchema)` to create a new message.
 */
export const StabilizationModeEnableSchema: GenMessage<StabilizationModeEnable> = /*@__PURE__*/
  messageDesc(file_jon_shared_cmd_cv, 5);

/**
 * @generated from message cmd.CV.StabilizationModeDisable
 */
export type StabilizationModeDisable = Message<"cmd.CV.StabilizationModeDisable"> & {
};

/**
 * Describes the message cmd.CV.StabilizationModeDisable.
 * Use `create(StabilizationModeDisableSchema)` to create a new message.
 */
export const StabilizationModeDisableSchema: GenMessage<StabilizationModeDisable> = /*@__PURE__*/
  messageDesc(file_jon_shared_cmd_cv, 6);

/**
 * @generated from message cmd.CV.RecognitionModeEnable
 */
export type RecognitionModeEnable = Message<"cmd.CV.RecognitionModeEnable"> & {
};

/**
 * Describes the message cmd.CV.RecognitionModeEnable.
 * Use `create(RecognitionModeEnableSchema)` to create a new message.
 */
export const RecognitionModeEnableSchema: GenMessage<RecognitionModeEnable> = /*@__PURE__*/
  messageDesc(file_jon_shared_cmd_cv, 7);

/**
 * @generated from message cmd.CV.RecognitionModeDisable
 */
export type RecognitionModeDisable = Message<"cmd.CV.RecognitionModeDisable"> & {
};

/**
 * Describes the message cmd.CV.RecognitionModeDisable.
 * Use `create(RecognitionModeDisableSchema)` to create a new message.
 */
export const RecognitionModeDisableSchema: GenMessage<RecognitionModeDisable> = /*@__PURE__*/
  messageDesc(file_jon_shared_cmd_cv, 8);

/**
 * @generated from message cmd.CV.SetAutoFocus
 */
export type SetAutoFocus = Message<"cmd.CV.SetAutoFocus"> & {
  /**
   * @generated from field: ser.JonGuiDataVideoChannel channel = 1;
   */
  channel: JonGuiDataVideoChannel;

  /**
   * @generated from field: bool value = 2;
   */
  value: boolean;
};

/**
 * Describes the message cmd.CV.SetAutoFocus.
 * Use `create(SetAutoFocusSchema)` to create a new message.
 */
export const SetAutoFocusSchema: GenMessage<SetAutoFocus> = /*@__PURE__*/
  messageDesc(file_jon_shared_cmd_cv, 9);

/**
 * @generated from message cmd.CV.StartTrackNDC
 */
export type StartTrackNDC = Message<"cmd.CV.StartTrackNDC"> & {
  /**
   * @generated from field: ser.JonGuiDataVideoChannel channel = 1;
   */
  channel: JonGuiDataVideoChannel;

  /**
   * @generated from field: double x = 2;
   */
  x: number;

  /**
   * @generated from field: double y = 3;
   */
  y: number;

  /**
   * TODO: Remove these fields after migration - now in Root message (fields 6-8)
   *
   * @generated from field: uint64 frame_time = 4;
   */
  frameTime: bigint;

  /**
   * System monotonic time from state when user performed action
   *
   * @generated from field: uint64 state_time = 5;
   */
  stateTime: bigint;
};

/**
 * Describes the message cmd.CV.StartTrackNDC.
 * Use `create(StartTrackNDCSchema)` to create a new message.
 */
export const StartTrackNDCSchema: GenMessage<StartTrackNDC> = /*@__PURE__*/
  messageDesc(file_jon_shared_cmd_cv, 10);

/**
 * @generated from message cmd.CV.StopTrack
 */
export type StopTrack = Message<"cmd.CV.StopTrack"> & {
};

/**
 * Describes the message cmd.CV.StopTrack.
 * Use `create(StopTrackSchema)` to create a new message.
 */
export const StopTrackSchema: GenMessage<StopTrack> = /*@__PURE__*/
  messageDesc(file_jon_shared_cmd_cv, 11);

/**
 * CV Bridge container control commands
 *
 * Starts the CV bridge container
 *
 * @generated from message cmd.CV.BridgeStart
 */
export type BridgeStart = Message<"cmd.CV.BridgeStart"> & {
};

/**
 * Describes the message cmd.CV.BridgeStart.
 * Use `create(BridgeStartSchema)` to create a new message.
 */
export const BridgeStartSchema: GenMessage<BridgeStart> = /*@__PURE__*/
  messageDesc(file_jon_shared_cmd_cv, 12);

/**
 * @generated from message cmd.CV.BridgeStop
 */
export type BridgeStop = Message<"cmd.CV.BridgeStop"> & {
  /**
   * If true, SIGKILL instead of SIGTERM
   *
   * @generated from field: bool force = 1;
   */
  force: boolean;
};

/**
 * Describes the message cmd.CV.BridgeStop.
 * Use `create(BridgeStopSchema)` to create a new message.
 */
export const BridgeStopSchema: GenMessage<BridgeStop> = /*@__PURE__*/
  messageDesc(file_jon_shared_cmd_cv, 13);

/**
 * @generated from message cmd.CV.BridgeRestart
 */
export type BridgeRestart = Message<"cmd.CV.BridgeRestart"> & {
  /**
   * If true, force stop before restart
   *
   * @generated from field: bool force = 1;
   */
  force: boolean;
};

/**
 * Describes the message cmd.CV.BridgeRestart.
 * Use `create(BridgeRestartSchema)` to create a new message.
 */
export const BridgeRestartSchema: GenMessage<BridgeRestart> = /*@__PURE__*/
  messageDesc(file_jon_shared_cmd_cv, 14);

