// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file jon_shared_data_lrf.proto (package ser, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "./buf/validate/validate_pb";
import type { JonGuiDataGpsFixType, JonGuiDataMeteo, JonGuiDatatLrfLaserPointerModes } from "./jon_shared_data_types_pb";
import { file_jon_shared_data_types } from "./jon_shared_data_types_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file jon_shared_data_lrf.proto.
 */
export const file_jon_shared_data_lrf: GenFile = /*@__PURE__*/
  fileDesc("Chlqb25fc2hhcmVkX2RhdGFfbHJmLnByb3RvEgNzZXIi3gIKDUpvbkd1aURhdGFMcmYSEwoLaXNfc2Nhbm5pbmcYASABKAgSFAoMaXNfbWVhc3VyaW5nGAIgASgIEhsKCm1lYXN1cmVfaWQYAyABKAVCB7pIBBoCKAASJQoGdGFyZ2V0GAQgASgLMhUuc2VyLkpvbkd1aURhdGFUYXJnZXQSRAoMcG9pbnRlcl9tb2RlGAUgASgOMiQuc2VyLkpvbkd1aURhdGF0THJmTGFzZXJQb2ludGVyTW9kZXNCCLpIBYIBAhABEhYKDmZvZ01vZGVFbmFibGVkGAYgASgIEhMKC2lzX3JlZmluaW5nGAcgASgIEh8KF2lzX2NvbnRpbnVvdXNfbWVhc3VyaW5nGAggASgIEhIKCmlzX3N0YXJ0ZWQYCSABKAgSIwoFbWV0ZW8YCiABKAsyFC5zZXIuSm9uR3VpRGF0YU1ldGVvEhEKCXNjYW5fbW9kZRgLIAEoBSLPBgoQSm9uR3VpRGF0YVRhcmdldBIaCgl0aW1lc3RhbXAYASABKANCB7pIBCICKAASMQoQdGFyZ2V0X2xvbmdpdHVkZRgCIAEoAUIXukgUEhIZAAAAAACAZkApAAAAAACAZsASMAoPdGFyZ2V0X2xhdGl0dWRlGAMgASgBQhe6SBQSEhkAAAAAAIBWQCkAAAAAAIBWwBIXCg90YXJnZXRfYWx0aXR1ZGUYBCABKAESMwoSb2JzZXJ2ZXJfbG9uZ2l0dWRlGAUgASgBQhe6SBQSEhkAAAAAAIBmQCkAAAAAAIBmwBIyChFvYnNlcnZlcl9sYXRpdHVkZRgGIAEoAUIXukgUEhIZAAAAAACAVkApAAAAAACAVsASGQoRb2JzZXJ2ZXJfYWx0aXR1ZGUYByABKAESMQoQb2JzZXJ2ZXJfYXppbXV0aBgIIAEoAUIXukgUEhIRAAAAAACAdkApAAAAAAAAAAASMwoSb2JzZXJ2ZXJfZWxldmF0aW9uGAkgASgBQhe6SBQSEhkAAAAAAIBWQCkAAAAAAIBWwBIuCg1vYnNlcnZlcl9iYW5rGAogASgBQhe6SBQSEhEAAAAAAIBmQCkAAAAAAIBmwBIsCgtkaXN0YW5jZV8yZBgLIAEoAUIXukgUEhIZAAAAAICEHkEpAAAAAAAAAAASLAoLZGlzdGFuY2VfM2IYDCABKAFCF7pIFBISGQAAAACAhB5BKQAAAAAAAAAAEisKCmRpc3RhbmNlX2MYFiABKAFCF7pIFBISGQAAAACAhB5BKQAAAAAAAAAAEkAKEW9ic2VydmVyX2ZpeF90eXBlGA0gASgOMhkuc2VyLkpvbkd1aURhdGFHcHNGaXhUeXBlQgq6SAeCAQQQASAAEhsKCnNlc3Npb25faWQYDiABKAVCB7pIBBoCKAASGgoJdGFyZ2V0X2lkGA8gASgFQge6SAQaAigAEiMKDHRhcmdldF9jb2xvchgQIAEoCzINLnNlci5SZ2JDb2xvchIMCgR0eXBlGBEgASgNEhIKCnV1aWRfcGFydDEYEiABKAUSEgoKdXVpZF9wYXJ0MhgTIAEoBRISCgp1dWlkX3BhcnQzGBQgASgFEhIKCnV1aWRfcGFydDQYFSABKAUiWAoIUmdiQ29sb3ISFwoDcmVkGAEgASgNQgq6SAcqBRj/ASgAEhkKBWdyZWVuGAIgASgNQgq6SAcqBRj/ASgAEhgKBGJsdWUYAyABKA1CCrpIByoFGP8BKABCS1pJZ2l0LWNvZGVjb21taXQuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb20vdjEvcmVwb3MvamV0dGlzb24vam9ucC9kYXRhL2xyZmIGcHJvdG8z", [file_buf_validate_validate, file_jon_shared_data_types]);

/**
 * @generated from message ser.JonGuiDataLrf
 */
export type JonGuiDataLrf = Message<"ser.JonGuiDataLrf"> & {
  /**
   * @generated from field: bool is_scanning = 1;
   */
  isScanning: boolean;

  /**
   * @generated from field: bool is_measuring = 2;
   */
  isMeasuring: boolean;

  /**
   * @generated from field: int32 measure_id = 3;
   */
  measureId: number;

  /**
   * @generated from field: ser.JonGuiDataTarget target = 4;
   */
  target?: JonGuiDataTarget;

  /**
   * @generated from field: ser.JonGuiDatatLrfLaserPointerModes pointer_mode = 5;
   */
  pointerMode: JonGuiDatatLrfLaserPointerModes;

  /**
   * @generated from field: bool fogModeEnabled = 6;
   */
  fogModeEnabled: boolean;

  /**
   * @generated from field: bool is_refining = 7;
   */
  isRefining: boolean;

  /**
   * @generated from field: bool is_continuous_measuring = 8;
   */
  isContinuousMeasuring: boolean;

  /**
   * @generated from field: bool is_started = 9;
   */
  isStarted: boolean;

  /**
   * @generated from field: ser.JonGuiDataMeteo meteo = 10;
   */
  meteo?: JonGuiDataMeteo;

  /**
   * Scanning mode frequency (0=off, 1=1Hz, 2=2Hz, 3=4Hz)
   *
   * @generated from field: int32 scan_mode = 11;
   */
  scanMode: number;
};

/**
 * Describes the message ser.JonGuiDataLrf.
 * Use `create(JonGuiDataLrfSchema)` to create a new message.
 */
export const JonGuiDataLrfSchema: GenMessage<JonGuiDataLrf> = /*@__PURE__*/
  messageDesc(file_jon_shared_data_lrf, 0);

/**
 * @generated from message ser.JonGuiDataTarget
 */
export type JonGuiDataTarget = Message<"ser.JonGuiDataTarget"> & {
  /**
   * @generated from field: int64 timestamp = 1;
   */
  timestamp: bigint;

  /**
   * @generated from field: double target_longitude = 2;
   */
  targetLongitude: number;

  /**
   * @generated from field: double target_latitude = 3;
   */
  targetLatitude: number;

  /**
   * @generated from field: double target_altitude = 4;
   */
  targetAltitude: number;

  /**
   * @generated from field: double observer_longitude = 5;
   */
  observerLongitude: number;

  /**
   * @generated from field: double observer_latitude = 6;
   */
  observerLatitude: number;

  /**
   * @generated from field: double observer_altitude = 7;
   */
  observerAltitude: number;

  /**
   * @generated from field: double observer_azimuth = 8;
   */
  observerAzimuth: number;

  /**
   * @generated from field: double observer_elevation = 9;
   */
  observerElevation: number;

  /**
   * @generated from field: double observer_bank = 10;
   */
  observerBank: number;

  /**
   * @generated from field: double distance_2d = 11;
   */
  distance2d: number;

  /**
   * @generated from field: double distance_3b = 12;
   */
  distance3b: number;

  /**
   * @generated from field: double distance_c = 22;
   */
  distanceC: number;

  /**
   * @generated from field: ser.JonGuiDataGpsFixType observer_fix_type = 13;
   */
  observerFixType: JonGuiDataGpsFixType;

  /**
   * @generated from field: int32 session_id = 14;
   */
  sessionId: number;

  /**
   * @generated from field: int32 target_id = 15;
   */
  targetId: number;

  /**
   * @generated from field: ser.RgbColor target_color = 16;
   */
  targetColor?: RgbColor;

  /**
   * @generated from field: uint32 type = 17;
   */
  type: number;

  /**
   * UUID as four fixed32 values (128 bits total)
   *
   * @generated from field: int32 uuid_part1 = 18;
   */
  uuidPart1: number;

  /**
   * @generated from field: int32 uuid_part2 = 19;
   */
  uuidPart2: number;

  /**
   * @generated from field: int32 uuid_part3 = 20;
   */
  uuidPart3: number;

  /**
   * @generated from field: int32 uuid_part4 = 21;
   */
  uuidPart4: number;
};

/**
 * Describes the message ser.JonGuiDataTarget.
 * Use `create(JonGuiDataTargetSchema)` to create a new message.
 */
export const JonGuiDataTargetSchema: GenMessage<JonGuiDataTarget> = /*@__PURE__*/
  messageDesc(file_jon_shared_data_lrf, 1);

/**
 * @generated from message ser.RgbColor
 */
export type RgbColor = Message<"ser.RgbColor"> & {
  /**
   * @generated from field: uint32 red = 1;
   */
  red: number;

  /**
   * @generated from field: uint32 green = 2;
   */
  green: number;

  /**
   * @generated from field: uint32 blue = 3;
   */
  blue: number;
};

/**
 * Describes the message ser.RgbColor.
 * Use `create(RgbColorSchema)` to create a new message.
 */
export const RgbColorSchema: GenMessage<RgbColor> = /*@__PURE__*/
  messageDesc(file_jon_shared_data_lrf, 2);

