// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file jon_shared_data_gps.proto (package ser, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "./buf/validate/validate_pb";
import type { JonGuiDataGpsFixType, JonGuiDataMeteo } from "./jon_shared_data_types_pb";
import { file_jon_shared_data_types } from "./jon_shared_data_types_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file jon_shared_data_gps.proto.
 */
export const file_jon_shared_data_gps: GenFile = /*@__PURE__*/
  fileDesc("Chlqb25fc2hhcmVkX2RhdGFfZ3BzLnByb3RvEgNzZXIiwQMKDUpvbkd1aURhdGFHcHMSKgoJbG9uZ2l0dWRlGAEgASgBQhe6SBQSEhkAAAAAAIBmQCkAAAAAAIBmwBIpCghsYXRpdHVkZRgCIAEoAUIXukgUEhIZAAAAAACAVkApAAAAAACAVsASKQoIYWx0aXR1ZGUYAyABKAFCF7pIFBISGQAAAAAAavhAKQAAAAAA4HrAEjEKEG1hbnVhbF9sb25naXR1ZGUYBCABKAFCF7pIFBISGQAAAAAAgGZAKQAAAAAAgGbAEjAKD21hbnVhbF9sYXRpdHVkZRgFIAEoAUIXukgUEhIZAAAAAACAVkApAAAAAACAVsASMAoPbWFudWFsX2FsdGl0dWRlGAYgASgBQhe6SBQSEhkAAAAAAGr4QCkAAAAAAOB6wBI3CghmaXhfdHlwZRgHIAEoDjIZLnNlci5Kb25HdWlEYXRhR3BzRml4VHlwZUIKukgHggEEEAEgABISCgp1c2VfbWFudWFsGAggASgIEhEKCXRpbWVzdGFtcBgJIAEoAxISCgppc19zdGFydGVkGAogASgIEiMKBW1ldGVvGAsgASgLMhQuc2VyLkpvbkd1aURhdGFNZXRlb0JLWklnaXQtY29kZWNvbW1pdC5ldS1jZW50cmFsLTEuYW1hem9uYXdzLmNvbS92MS9yZXBvcy9qZXR0aXNvbi9qb25wL2RhdGEvZ3BzYgZwcm90bzM", [file_buf_validate_validate, file_jon_shared_data_types]);

/**
 * @generated from message ser.JonGuiDataGps
 */
export type JonGuiDataGps = Message<"ser.JonGuiDataGps"> & {
  /**
   * @generated from field: double longitude = 1;
   */
  longitude: number;

  /**
   * @generated from field: double latitude = 2;
   */
  latitude: number;

  /**
   * @generated from field: double altitude = 3;
   */
  altitude: number;

  /**
   * @generated from field: double manual_longitude = 4;
   */
  manualLongitude: number;

  /**
   * @generated from field: double manual_latitude = 5;
   */
  manualLatitude: number;

  /**
   * @generated from field: double manual_altitude = 6;
   */
  manualAltitude: number;

  /**
   * @generated from field: ser.JonGuiDataGpsFixType fix_type = 7;
   */
  fixType: JonGuiDataGpsFixType;

  /**
   * @generated from field: bool use_manual = 8;
   */
  useManual: boolean;

  /**
   * GPS timestamp from satellite (Unix time in seconds)
   *
   * @generated from field: int64 timestamp = 9;
   */
  timestamp: bigint;

  /**
   * @generated from field: bool is_started = 10;
   */
  isStarted: boolean;

  /**
   * @generated from field: ser.JonGuiDataMeteo meteo = 11;
   */
  meteo?: JonGuiDataMeteo;
};

/**
 * Describes the message ser.JonGuiDataGps.
 * Use `create(JonGuiDataGpsSchema)` to create a new message.
 */
export const JonGuiDataGpsSchema: GenMessage<JonGuiDataGps> = /*@__PURE__*/
  messageDesc(file_jon_shared_data_gps, 0);

