// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file jon_shared_data_day_cam_glass_heater.proto (package ser, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "./buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file jon_shared_data_day_cam_glass_heater.proto.
 */
export const file_jon_shared_data_day_cam_glass_heater: GenFile = /*@__PURE__*/
  fileDesc("Cipqb25fc2hhcmVkX2RhdGFfZGF5X2NhbV9nbGFzc19oZWF0ZXIucHJvdG8SA3NlciJ/ChtKb25HdWlEYXRhRGF5Q2FtR2xhc3NIZWF0ZXISUAoLdGVtcGVyYXR1cmUYASABKAFCO7pIOBI2GcP1KFyPooRAKWZmZmZmEnHASQAAAAAAADTASQAAAAAAAAAASQAAAAAAADlASQAAAAAAAFlAEg4KBnN0YXR1cxgCIAEoCEJcWlpnaXQtY29kZWNvbW1pdC5ldS1jZW50cmFsLTEuYW1hem9uYXdzLmNvbS92MS9yZXBvcy9qZXR0aXNvbi9qb25wL2RhdGEvZGF5X2NhbV9nbGFzc19oZWF0ZXJiBnByb3RvMw", [file_buf_validate_validate]);

/**
 * @generated from message ser.JonGuiDataDayCamGlassHeater
 */
export type JonGuiDataDayCamGlassHeater = Message<"ser.JonGuiDataDayCamGlassHeater"> & {
  /**
   * @generated from field: double temperature = 1;
   */
  temperature: number;

  /**
   * @generated from field: bool status = 2;
   */
  status: boolean;
};

/**
 * Describes the message ser.JonGuiDataDayCamGlassHeater.
 * Use `create(JonGuiDataDayCamGlassHeaterSchema)` to create a new message.
 */
export const JonGuiDataDayCamGlassHeaterSchema: GenMessage<JonGuiDataDayCamGlassHeater> = /*@__PURE__*/
  messageDesc(file_jon_shared_data_day_cam_glass_heater, 0);

