// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file jon_video_meta.proto (package jon.video, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "./buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file jon_video_meta.proto.
 */
export const file_jon_video_meta: GenFile = /*@__PURE__*/
  fileDesc("ChRqb25fdmlkZW9fbWV0YS5wcm90bxIJam9uLnZpZGVvIm8KEFZpZGVvTWV0YVJlcXVlc3QSKwoFcmFuZ2UYASABKAsyGi5qb24udmlkZW8uVmlkZW9SYW5nZVF1ZXJ5SAASJQoDaWRzGAIgASgLMhYuam9uLnZpZGVvLlZpZGVvSWRMaXN0SABCBwoFcXVlcnkiJgoLVmlkZW9JZExpc3QSFwoFdXVpZHMYASADKAlCCLpIBZIBAggBIscBCg9WaWRlb1JhbmdlUXVlcnkSIAoPc3RhcnRfdGltZXN0YW1wGAEgASgEQge6SAQyAigAEh4KDWVuZF90aW1lc3RhbXAYAiABKARCB7pIBDICKAASGAoLc291cmNlX3R5cGUYAyABKAlIAIgBARIeCgVsaW1pdBgEIAEoDUIKukgHKgUY6AcoAUgBiAEBEhMKBm9mZnNldBgFIAEoDUgCiAEBQg4KDF9zb3VyY2VfdHlwZUIICgZfbGltaXRCCQoHX29mZnNldCJ1ChFWaWRlb01ldGFSZXNwb25zZRIkCgZ2aWRlb3MYASADKAsyFC5qb24udmlkZW8uVmlkZW9NZXRhEiUKBmVycm9ycxgCIAMoCzIVLmpvbi52aWRlby5WaWRlb0Vycm9yEhMKC3RvdGFsX2NvdW50GAMgASgNIoICCglWaWRlb01ldGESDAoEdXVpZBgBIAEoCRISCgpzZXNzaW9uX2lkGAIgASgFEhEKCXRpbWVzdGFtcBgDIAEoBBIUCgxzdG9yYWdlX3BhdGgYBCABKAkSEwoLc291cmNlX3R5cGUYBSABKAkSEwoLZnJhbWVfY291bnQYBiABKA0SEwoLZHVyYXRpb25fbXMYByABKA0SDQoFd2lkdGgYCCABKA0SDgoGaGVpZ2h0GAkgASgNEgsKA2RzaRgKIAEoDBIRCgl0aW1lc2NhbGUYCyABKA0SLAoMc2FtcGxlX3RhYmxlGAwgASgLMhYuam9uLnZpZGVvLlNhbXBsZVRhYmxlIpkBCgtTYW1wbGVUYWJsZRIUCgxzYW1wbGVfc2l6ZXMYASADKA0SFQoNY2h1bmtfb2Zmc2V0cxgCIAMoBBIUCgxzYW1wbGVfdGltZXMYAyADKA0SFAoMc3luY19zYW1wbGVzGAQgAygNEjEKD3NhbXBsZV90b19jaHVuaxgFIAMoCzIYLmpvbi52aWRlby5TYW1wbGVUb0NodW5rImEKDVNhbXBsZVRvQ2h1bmsSEwoLZmlyc3RfY2h1bmsYASABKA0SGQoRc2FtcGxlc19wZXJfY2h1bmsYAiABKA0SIAoYc2FtcGxlX2Rlc2NyaXB0aW9uX2luZGV4GAMgASgNInYKClZpZGVvRXJyb3ISDAoEdXVpZBgBIAEoCRIUCgxzdG9yYWdlX3BhdGgYAiABKAkSLQoKZXJyb3JfdHlwZRgDIAEoDjIZLmpvbi52aWRlby5WaWRlb0Vycm9yVHlwZRIVCg1lcnJvcl9tZXNzYWdlGAQgASgJKtkBCg5WaWRlb0Vycm9yVHlwZRIgChxWSURFT19FUlJPUl9UWVBFX1VOU1BFQ0lGSUVEEAASIwofVklERU9fRVJST1JfVFlQRV9GSUxFX05PVF9GT1VORBABEh8KG1ZJREVPX0VSUk9SX1RZUEVfRU1QVFlfRklMRRACEhwKGFZJREVPX0VSUk9SX1RZUEVfTk9fTU9PVhADEiEKHVZJREVPX0VSUk9SX1RZUEVfSU5WQUxJRF9NT09WEAQSHgoaVklERU9fRVJST1JfVFlQRV9UUlVOQ0FURUQQBUJIWkZnaXQtY29kZWNvbW1pdC5ldS1jZW50cmFsLTEuYW1hem9uYXdzLmNvbS92MS9yZXBvcy9qZXR0aXNvbi9qb25wL3ZpZGVvYgZwcm90bzM", [file_buf_validate_validate]);

/**
 * Request message for video metadata retrieval
 *
 * @generated from message jon.video.VideoMetaRequest
 */
export type VideoMetaRequest = Message<"jon.video.VideoMetaRequest"> & {
  /**
   * @generated from oneof jon.video.VideoMetaRequest.query
   */
  query: {
    /**
     * Time-based range query
     *
     * @generated from field: jon.video.VideoRangeQuery range = 1;
     */
    value: VideoRangeQuery;
    case: "range";
  } | {
    /**
     * Explicit UUID list
     *
     * @generated from field: jon.video.VideoIdList ids = 2;
     */
    value: VideoIdList;
    case: "ids";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message jon.video.VideoMetaRequest.
 * Use `create(VideoMetaRequestSchema)` to create a new message.
 */
export const VideoMetaRequestSchema: GenMessage<VideoMetaRequest> = /*@__PURE__*/
  messageDesc(file_jon_video_meta, 0);

/**
 * List of video UUIDs for explicit selection
 *
 * @generated from message jon.video.VideoIdList
 */
export type VideoIdList = Message<"jon.video.VideoIdList"> & {
  /**
   * @generated from field: repeated string uuids = 1;
   */
  uuids: string[];
};

/**
 * Describes the message jon.video.VideoIdList.
 * Use `create(VideoIdListSchema)` to create a new message.
 */
export const VideoIdListSchema: GenMessage<VideoIdList> = /*@__PURE__*/
  messageDesc(file_jon_video_meta, 1);

/**
 * Time-based range query for selecting videos
 *
 * @generated from message jon.video.VideoRangeQuery
 */
export type VideoRangeQuery = Message<"jon.video.VideoRangeQuery"> & {
  /**
   * Unix seconds
   *
   * @generated from field: uint64 start_timestamp = 1;
   */
  startTimestamp: bigint;

  /**
   * Unix seconds
   *
   * @generated from field: uint64 end_timestamp = 2;
   */
  endTimestamp: bigint;

  /**
   * "day" or "heat" filter
   *
   * @generated from field: optional string source_type = 3;
   */
  sourceType?: string;

  /**
   * @generated from field: optional uint32 limit = 4;
   */
  limit?: number;

  /**
   * Pagination offset
   *
   * @generated from field: optional uint32 offset = 5;
   */
  offset?: number;
};

/**
 * Describes the message jon.video.VideoRangeQuery.
 * Use `create(VideoRangeQuerySchema)` to create a new message.
 */
export const VideoRangeQuerySchema: GenMessage<VideoRangeQuery> = /*@__PURE__*/
  messageDesc(file_jon_video_meta, 2);

/**
 * Response containing video metadata and any errors
 *
 * @generated from message jon.video.VideoMetaResponse
 */
export type VideoMetaResponse = Message<"jon.video.VideoMetaResponse"> & {
  /**
   * Successfully processed videos
   *
   * @generated from field: repeated jon.video.VideoMeta videos = 1;
   */
  videos: VideoMeta[];

  /**
   * Errors for failed videos
   *
   * @generated from field: repeated jon.video.VideoError errors = 2;
   */
  errors: VideoError[];

  /**
   * Total matching (before limit)
   *
   * @generated from field: uint32 total_count = 3;
   */
  totalCount: number;
};

/**
 * Describes the message jon.video.VideoMetaResponse.
 * Use `create(VideoMetaResponseSchema)` to create a new message.
 */
export const VideoMetaResponseSchema: GenMessage<VideoMetaResponse> = /*@__PURE__*/
  messageDesc(file_jon_video_meta, 3);

/**
 * Metadata for a single video including MOOV data
 *
 * @generated from message jon.video.VideoMeta
 */
export type VideoMeta = Message<"jon.video.VideoMeta"> & {
  /**
   * @generated from field: string uuid = 1;
   */
  uuid: string;

  /**
   * @generated from field: int32 session_id = 2;
   */
  sessionId: number;

  /**
   * Unix seconds
   *
   * @generated from field: uint64 timestamp = 3;
   */
  timestamp: bigint;

  /**
   * Directory path to video files
   *
   * @generated from field: string storage_path = 4;
   */
  storagePath: string;

  /**
   * "day" or "heat"
   *
   * @generated from field: string source_type = 5;
   */
  sourceType: string;

  /**
   * MOOV extracted data
   *
   * @generated from field: uint32 frame_count = 6;
   */
  frameCount: number;

  /**
   * @generated from field: uint32 duration_ms = 7;
   */
  durationMs: number;

  /**
   * @generated from field: uint32 width = 8;
   */
  width: number;

  /**
   * @generated from field: uint32 height = 9;
   */
  height: number;

  /**
   * avcC decoder specific info
   *
   * @generated from field: bytes dsi = 10;
   */
  dsi: Uint8Array;

  /**
   * Media timescale from mdhd
   *
   * @generated from field: uint32 timescale = 11;
   */
  timescale: number;

  /**
   * Sample table (always included for playback)
   *
   * @generated from field: jon.video.SampleTable sample_table = 12;
   */
  sampleTable?: SampleTable;
};

/**
 * Describes the message jon.video.VideoMeta.
 * Use `create(VideoMetaSchema)` to create a new message.
 */
export const VideoMetaSchema: GenMessage<VideoMeta> = /*@__PURE__*/
  messageDesc(file_jon_video_meta, 4);

/**
 * MP4 sample table data extracted from MOOV
 *
 * @generated from message jon.video.SampleTable
 */
export type SampleTable = Message<"jon.video.SampleTable"> & {
  /**
   * Frame sizes in bytes (stsz)
   *
   * @generated from field: repeated uint32 sample_sizes = 1;
   */
  sampleSizes: number[];

  /**
   * Byte offsets in file (stco/co64)
   *
   * @generated from field: repeated uint64 chunk_offsets = 2;
   */
  chunkOffsets: bigint[];

  /**
   * Decoding timestamps (stts deltas)
   *
   * @generated from field: repeated uint32 sample_times = 3;
   */
  sampleTimes: number[];

  /**
   * Keyframe indices, 1-based (stss)
   *
   * @generated from field: repeated uint32 sync_samples = 4;
   */
  syncSamples: number[];

  /**
   * Sample-to-chunk mapping (stsc)
   *
   * @generated from field: repeated jon.video.SampleToChunk sample_to_chunk = 5;
   */
  sampleToChunk: SampleToChunk[];
};

/**
 * Describes the message jon.video.SampleTable.
 * Use `create(SampleTableSchema)` to create a new message.
 */
export const SampleTableSchema: GenMessage<SampleTable> = /*@__PURE__*/
  messageDesc(file_jon_video_meta, 5);

/**
 * Sample-to-chunk box entry
 *
 * @generated from message jon.video.SampleToChunk
 */
export type SampleToChunk = Message<"jon.video.SampleToChunk"> & {
  /**
   * @generated from field: uint32 first_chunk = 1;
   */
  firstChunk: number;

  /**
   * @generated from field: uint32 samples_per_chunk = 2;
   */
  samplesPerChunk: number;

  /**
   * @generated from field: uint32 sample_description_index = 3;
   */
  sampleDescriptionIndex: number;
};

/**
 * Describes the message jon.video.SampleToChunk.
 * Use `create(SampleToChunkSchema)` to create a new message.
 */
export const SampleToChunkSchema: GenMessage<SampleToChunk> = /*@__PURE__*/
  messageDesc(file_jon_video_meta, 6);

/**
 * Error information for a video that failed processing
 *
 * @generated from message jon.video.VideoError
 */
export type VideoError = Message<"jon.video.VideoError"> & {
  /**
   * @generated from field: string uuid = 1;
   */
  uuid: string;

  /**
   * @generated from field: string storage_path = 2;
   */
  storagePath: string;

  /**
   * @generated from field: jon.video.VideoErrorType error_type = 3;
   */
  errorType: VideoErrorType;

  /**
   * @generated from field: string error_message = 4;
   */
  errorMessage: string;
};

/**
 * Describes the message jon.video.VideoError.
 * Use `create(VideoErrorSchema)` to create a new message.
 */
export const VideoErrorSchema: GenMessage<VideoError> = /*@__PURE__*/
  messageDesc(file_jon_video_meta, 7);

/**
 * Types of errors that can occur during video metadata extraction
 *
 * @generated from enum jon.video.VideoErrorType
 */
export enum VideoErrorType {
  /**
   * @generated from enum value: VIDEO_ERROR_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: VIDEO_ERROR_TYPE_FILE_NOT_FOUND = 1;
   */
  FILE_NOT_FOUND = 1,

  /**
   * @generated from enum value: VIDEO_ERROR_TYPE_EMPTY_FILE = 2;
   */
  EMPTY_FILE = 2,

  /**
   * @generated from enum value: VIDEO_ERROR_TYPE_NO_MOOV = 3;
   */
  NO_MOOV = 3,

  /**
   * @generated from enum value: VIDEO_ERROR_TYPE_INVALID_MOOV = 4;
   */
  INVALID_MOOV = 4,

  /**
   * @generated from enum value: VIDEO_ERROR_TYPE_TRUNCATED = 5;
   */
  TRUNCATED = 5,
}

/**
 * Describes the enum jon.video.VideoErrorType.
 */
export const VideoErrorTypeSchema: GenEnum<VideoErrorType> = /*@__PURE__*/
  enumDesc(file_jon_video_meta, 0);

