// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file jon_shared_data_heater.proto (package ser, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "./buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file jon_shared_data_heater.proto.
 */
export const file_jon_shared_data_heater: GenFile = /*@__PURE__*/
  fileDesc("Chxqb25fc2hhcmVkX2RhdGFfaGVhdGVyLnByb3RvEgNzZXIikgEKHUpvbkd1aURhdGFIZWF0ZXJDaGFubmVsU3RhdHVzEhMKC3RlbXBlcmF0dXJlGAEgASgCEiUKEWFwcGxpZWRfdm9sdGFnZV9WGAIgASgCQgq6SAcKBS0AAAAAEiQKEHRhcmdldF92b2x0YWdlX1YYAyABKAJCCrpIBwoFLQAAAAASDwoHZW5hYmxlZBgEIAEoCCKzAQoQSm9uR3VpRGF0YUhlYXRlchIhCg1idXNfdm9sdGFnZV9WGAEgASgCQgq6SAcKBS0AAAAAEh0KCWN1cnJlbnRfQRgCIAEoAkIKukgHCgUtAAAAABIbCgdwb3dlcl9XGAMgASgCQgq6SAcKBS0AAAAAEkAKCGNoYW5uZWxzGAQgAygLMiIuc2VyLkpvbkd1aURhdGFIZWF0ZXJDaGFubmVsU3RhdHVzQgq6SAeSAQQIAxADQk5aTGdpdC1jb2RlY29tbWl0LmV1LWNlbnRyYWwtMS5hbWF6b25hd3MuY29tL3YxL3JlcG9zL2pldHRpc29uL2pvbnAvZGF0YS9oZWF0ZXJiBnByb3RvMw", [file_buf_validate_validate]);

/**
 * HeaterChannelStatus represents the state of a single heating channel
 *
 * @generated from message ser.JonGuiDataHeaterChannelStatus
 */
export type JonGuiDataHeaterChannelStatus = Message<"ser.JonGuiDataHeaterChannelStatus"> & {
  /**
   * @generated from field: float temperature = 1;
   */
  temperature: number;

  /**
   * @generated from field: float applied_voltage_V = 2;
   */
  appliedVoltageV: number;

  /**
   * @generated from field: float target_voltage_V = 3;
   */
  targetVoltageV: number;

  /**
   * @generated from field: bool enabled = 4;
   */
  enabled: boolean;
};

/**
 * Describes the message ser.JonGuiDataHeaterChannelStatus.
 * Use `create(JonGuiDataHeaterChannelStatusSchema)` to create a new message.
 */
export const JonGuiDataHeaterChannelStatusSchema: GenMessage<JonGuiDataHeaterChannelStatus> = /*@__PURE__*/
  messageDesc(file_jon_shared_data_heater, 0);

/**
 * JonGuiDataHeater contains the complete heater subsystem status
 *
 * @generated from message ser.JonGuiDataHeater
 */
export type JonGuiDataHeater = Message<"ser.JonGuiDataHeater"> & {
  /**
   * @generated from field: float bus_voltage_V = 1;
   */
  busVoltageV: number;

  /**
   * @generated from field: float current_A = 2;
   */
  currentA: number;

  /**
   * @generated from field: float power_W = 3;
   */
  powerW: number;

  /**
   * @generated from field: repeated ser.JonGuiDataHeaterChannelStatus channels = 4;
   */
  channels: JonGuiDataHeaterChannelStatus[];
};

/**
 * Describes the message ser.JonGuiDataHeater.
 * Use `create(JonGuiDataHeaterSchema)` to create a new message.
 */
export const JonGuiDataHeaterSchema: GenMessage<JonGuiDataHeater> = /*@__PURE__*/
  messageDesc(file_jon_shared_data_heater, 1);

