// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file jon_shared_cmd_lrf_align.proto (package cmd.Lrf_calib, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "./buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file jon_shared_cmd_lrf_align.proto.
 */
export const file_jon_shared_cmd_lrf_align: GenFile = /*@__PURE__*/
  fileDesc("Ch5qb25fc2hhcmVkX2NtZF9scmZfYWxpZ24ucHJvdG8SDWNtZC5McmZfY2FsaWIiYAoEUm9vdBIlCgNkYXkYASABKAsyFi5jbWQuTHJmX2NhbGliLk9mZnNldHNIABImCgRoZWF0GAIgASgLMhYuY21kLkxyZl9jYWxpYi5PZmZzZXRzSABCCQoHY2hhbm5lbCLLAQoHT2Zmc2V0cxIoCgNzZXQYASABKAsyGS5jbWQuTHJmX2NhbGliLlNldE9mZnNldHNIABIqCgRzYXZlGAIgASgLMhouY21kLkxyZl9jYWxpYi5TYXZlT2Zmc2V0c0gAEiwKBXJlc2V0GAMgASgLMhsuY21kLkxyZl9jYWxpYi5SZXNldE9mZnNldHNIABIuCgVzaGlmdBgEIAEoCzIdLmNtZC5McmZfY2FsaWIuU2hpZnRPZmZzZXRzQnlIAEIMCgNjbWQSBbpIAggBIkwKClNldE9mZnNldHMSHgoBeBgBIAEoBUITukgQGg4YgA8ogPH/////////ARIeCgF5GAIgASgFQhO6SBAaDhi4CCjI9/////////8BIlAKDlNoaWZ0T2Zmc2V0c0J5Eh4KAXgYASABKAVCE7pIEBoOGIAPKIDx/////////wESHgoBeRgCIAEoBUITukgQGg4YuAgoyPf/////////ASIOCgxSZXNldE9mZnNldHMiDQoLU2F2ZU9mZnNldHNCUFpOZ2l0LWNvZGVjb21taXQuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb20vdjEvcmVwb3MvamV0dGlzb24vam9ucC9jbWQvbHJmX2FsaWduYgZwcm90bzM", [file_buf_validate_validate]);

/**
 * @generated from message cmd.Lrf_calib.Root
 */
export type Root = Message<"cmd.Lrf_calib.Root"> & {
  /**
   * @generated from oneof cmd.Lrf_calib.Root.channel
   */
  channel: {
    /**
     * @generated from field: cmd.Lrf_calib.Offsets day = 1;
     */
    value: Offsets;
    case: "day";
  } | {
    /**
     * @generated from field: cmd.Lrf_calib.Offsets heat = 2;
     */
    value: Offsets;
    case: "heat";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message cmd.Lrf_calib.Root.
 * Use `create(RootSchema)` to create a new message.
 */
export const RootSchema: GenMessage<Root> = /*@__PURE__*/
  messageDesc(file_jon_shared_cmd_lrf_align, 0);

/**
 * @generated from message cmd.Lrf_calib.Offsets
 */
export type Offsets = Message<"cmd.Lrf_calib.Offsets"> & {
  /**
   * @generated from oneof cmd.Lrf_calib.Offsets.cmd
   */
  cmd: {
    /**
     * @generated from field: cmd.Lrf_calib.SetOffsets set = 1;
     */
    value: SetOffsets;
    case: "set";
  } | {
    /**
     * @generated from field: cmd.Lrf_calib.SaveOffsets save = 2;
     */
    value: SaveOffsets;
    case: "save";
  } | {
    /**
     * @generated from field: cmd.Lrf_calib.ResetOffsets reset = 3;
     */
    value: ResetOffsets;
    case: "reset";
  } | {
    /**
     * @generated from field: cmd.Lrf_calib.ShiftOffsetsBy shift = 4;
     */
    value: ShiftOffsetsBy;
    case: "shift";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message cmd.Lrf_calib.Offsets.
 * Use `create(OffsetsSchema)` to create a new message.
 */
export const OffsetsSchema: GenMessage<Offsets> = /*@__PURE__*/
  messageDesc(file_jon_shared_cmd_lrf_align, 1);

/**
 * @generated from message cmd.Lrf_calib.SetOffsets
 */
export type SetOffsets = Message<"cmd.Lrf_calib.SetOffsets"> & {
  /**
   * @generated from field: int32 x = 1;
   */
  x: number;

  /**
   * @generated from field: int32 y = 2;
   */
  y: number;
};

/**
 * Describes the message cmd.Lrf_calib.SetOffsets.
 * Use `create(SetOffsetsSchema)` to create a new message.
 */
export const SetOffsetsSchema: GenMessage<SetOffsets> = /*@__PURE__*/
  messageDesc(file_jon_shared_cmd_lrf_align, 2);

/**
 * @generated from message cmd.Lrf_calib.ShiftOffsetsBy
 */
export type ShiftOffsetsBy = Message<"cmd.Lrf_calib.ShiftOffsetsBy"> & {
  /**
   * @generated from field: int32 x = 1;
   */
  x: number;

  /**
   * @generated from field: int32 y = 2;
   */
  y: number;
};

/**
 * Describes the message cmd.Lrf_calib.ShiftOffsetsBy.
 * Use `create(ShiftOffsetsBySchema)` to create a new message.
 */
export const ShiftOffsetsBySchema: GenMessage<ShiftOffsetsBy> = /*@__PURE__*/
  messageDesc(file_jon_shared_cmd_lrf_align, 3);

/**
 * @generated from message cmd.Lrf_calib.ResetOffsets
 */
export type ResetOffsets = Message<"cmd.Lrf_calib.ResetOffsets"> & {
};

/**
 * Describes the message cmd.Lrf_calib.ResetOffsets.
 * Use `create(ResetOffsetsSchema)` to create a new message.
 */
export const ResetOffsetsSchema: GenMessage<ResetOffsets> = /*@__PURE__*/
  messageDesc(file_jon_shared_cmd_lrf_align, 4);

/**
 * @generated from message cmd.Lrf_calib.SaveOffsets
 */
export type SaveOffsets = Message<"cmd.Lrf_calib.SaveOffsets"> & {
};

/**
 * Describes the message cmd.Lrf_calib.SaveOffsets.
 * Use `create(SaveOffsetsSchema)` to create a new message.
 */
export const SaveOffsetsSchema: GenMessage<SaveOffsets> = /*@__PURE__*/
  messageDesc(file_jon_shared_cmd_lrf_align, 5);

