// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file jon_shared_data_compass.proto (package ser, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "./buf/validate/validate_pb";
import type { JonGuiDataMeteo } from "./jon_shared_data_types_pb";
import { file_jon_shared_data_types } from "./jon_shared_data_types_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file jon_shared_data_compass.proto.
 */
export const file_jon_shared_data_compass: GenFile = /*@__PURE__*/
  fileDesc("Ch1qb25fc2hhcmVkX2RhdGFfY29tcGFzcy5wcm90bxIDc2VyIqEEChFKb25HdWlEYXRhQ29tcGFzcxJMCgdhemltdXRoGAEgASgBQju6SDgSNhEAAAAAAIB2QCkAAAAAAAAAAEkAAAAAAAAAAEkAAAAAAKBWQEkAAAAAAIBmQEkAAAAAAOBwQBJFCgllbGV2YXRpb24YAiABKAFCMrpILxItGQAAAAAAgFZAKQAAAAAAgFbASQAAAAAAgEbASQAAAAAAAAAASQAAAAAAgEZAEkAKBGJhbmsYAyABKAFCMrpILxItEQAAAAAAgGZAKQAAAAAAgGbASQAAAAAAgFbASQAAAAAAAAAASQAAAAAAgFZAEkkKDW9mZnNldEF6aW11dGgYBCABKAFCMrpILxItEQAAAAAAgGZAKQAAAAAAgGbASQAAAAAAgEbASQAAAAAAAAAASQAAAAAAgEZAEksKD29mZnNldEVsZXZhdGlvbhgFIAEoAUIyukgvEi0ZAAAAAACAVkApAAAAAACAVsBJAAAAAAAAPsBJAAAAAAAAAABJAAAAAAAAPkASTwoTbWFnbmV0aWNEZWNsaW5hdGlvbhgGIAEoAUIyukgvEi0RAAAAAACAZkApAAAAAACAZsBJAAAAAAAALsBJAAAAAAAAAABJAAAAAAAALkASEwoLY2FsaWJyYXRpbmcYByABKAgSEgoKaXNfc3RhcnRlZBgIIAEoCBIjCgVtZXRlbxgJIAEoCzIULnNlci5Kb25HdWlEYXRhTWV0ZW9CT1pNZ2l0LWNvZGVjb21taXQuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb20vdjEvcmVwb3MvamV0dGlzb24vam9ucC9kYXRhL2NvbXBhc3NiBnByb3RvMw", [file_buf_validate_validate, file_jon_shared_data_types]);

/**
 * @generated from message ser.JonGuiDataCompass
 */
export type JonGuiDataCompass = Message<"ser.JonGuiDataCompass"> & {
  /**
   * @generated from field: double azimuth = 1;
   */
  azimuth: number;

  /**
   * @generated from field: double elevation = 2;
   */
  elevation: number;

  /**
   * @generated from field: double bank = 3;
   */
  bank: number;

  /**
   * @generated from field: double offsetAzimuth = 4;
   */
  offsetAzimuth: number;

  /**
   * @generated from field: double offsetElevation = 5;
   */
  offsetElevation: number;

  /**
   * @generated from field: double magneticDeclination = 6;
   */
  magneticDeclination: number;

  /**
   * @generated from field: bool calibrating = 7;
   */
  calibrating: boolean;

  /**
   * @generated from field: bool is_started = 8;
   */
  isStarted: boolean;

  /**
   * @generated from field: ser.JonGuiDataMeteo meteo = 9;
   */
  meteo?: JonGuiDataMeteo;
};

/**
 * Describes the message ser.JonGuiDataCompass.
 * Use `create(JonGuiDataCompassSchema)` to create a new message.
 */
export const JonGuiDataCompassSchema: GenMessage<JonGuiDataCompass> = /*@__PURE__*/
  messageDesc(file_jon_shared_data_compass, 0);

