// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file jon_shared_cmd_osd.proto (package cmd.OSD, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "./buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file jon_shared_cmd_osd.proto.
 */
export const file_jon_shared_cmd_osd: GenFile = /*@__PURE__*/
  fileDesc("Chhqb25fc2hhcmVkX2NtZF9vc2QucHJvdG8SB2NtZC5PU0Qi8gMKBFJvb3QSOQoTc2hvd19kZWZhdWx0X3NjcmVlbhgBIAEoCzIaLmNtZC5PU0QuU2hvd0RlZmF1bHRTY3JlZW5IABJAChdzaG93X2xyZl9tZWFzdXJlX3NjcmVlbhgCIAEoCzIdLmNtZC5PU0QuU2hvd0xSRk1lYXN1cmVTY3JlZW5IABI+ChZzaG93X2xyZl9yZXN1bHRfc2NyZWVuGAMgASgLMhwuY21kLk9TRC5TaG93TFJGUmVzdWx0U2NyZWVuSAASUwohc2hvd19scmZfcmVzdWx0X3NpbXBsaWZpZWRfc2NyZWVuGAQgASgLMiYuY21kLk9TRC5TaG93TFJGUmVzdWx0U2ltcGxpZmllZFNjcmVlbkgAEjEKD2VuYWJsZV9oZWF0X29zZBgFIAEoCzIWLmNtZC5PU0QuRW5hYmxlSGVhdE9TREgAEjMKEGRpc2FibGVfaGVhdF9vc2QYBiABKAsyFy5jbWQuT1NELkRpc2FibGVIZWF0T1NESAASLwoOZW5hYmxlX2RheV9vc2QYByABKAsyFS5jbWQuT1NELkVuYWJsZURheU9TREgAEjEKD2Rpc2FibGVfZGF5X29zZBgIIAEoCzIWLmNtZC5PU0QuRGlzYWJsZURheU9TREgAQgwKA2NtZBIFukgCCAEiEwoRU2hvd0RlZmF1bHRTY3JlZW4iFgoUU2hvd0xSRk1lYXN1cmVTY3JlZW4iFQoTU2hvd0xSRlJlc3VsdFNjcmVlbiIfCh1TaG93TFJGUmVzdWx0U2ltcGxpZmllZFNjcmVlbiIPCg1FbmFibGVIZWF0T1NEIhAKDkRpc2FibGVIZWF0T1NEIg4KDEVuYWJsZURheU9TRCIPCg1EaXNhYmxlRGF5T1NEQkpaSGdpdC1jb2RlY29tbWl0LmV1LWNlbnRyYWwtMS5hbWF6b25hd3MuY29tL3YxL3JlcG9zL2pldHRpc29uL2pvbnAvY21kL29zZGIGcHJvdG8z", [file_buf_validate_validate]);

/**
 * @generated from message cmd.OSD.Root
 */
export type Root = Message<"cmd.OSD.Root"> & {
  /**
   * @generated from oneof cmd.OSD.Root.cmd
   */
  cmd: {
    /**
     * @generated from field: cmd.OSD.ShowDefaultScreen show_default_screen = 1;
     */
    value: ShowDefaultScreen;
    case: "showDefaultScreen";
  } | {
    /**
     * @generated from field: cmd.OSD.ShowLRFMeasureScreen show_lrf_measure_screen = 2;
     */
    value: ShowLRFMeasureScreen;
    case: "showLrfMeasureScreen";
  } | {
    /**
     * @generated from field: cmd.OSD.ShowLRFResultScreen show_lrf_result_screen = 3;
     */
    value: ShowLRFResultScreen;
    case: "showLrfResultScreen";
  } | {
    /**
     * @generated from field: cmd.OSD.ShowLRFResultSimplifiedScreen show_lrf_result_simplified_screen = 4;
     */
    value: ShowLRFResultSimplifiedScreen;
    case: "showLrfResultSimplifiedScreen";
  } | {
    /**
     * @generated from field: cmd.OSD.EnableHeatOSD enable_heat_osd = 5;
     */
    value: EnableHeatOSD;
    case: "enableHeatOsd";
  } | {
    /**
     * @generated from field: cmd.OSD.DisableHeatOSD disable_heat_osd = 6;
     */
    value: DisableHeatOSD;
    case: "disableHeatOsd";
  } | {
    /**
     * @generated from field: cmd.OSD.EnableDayOSD enable_day_osd = 7;
     */
    value: EnableDayOSD;
    case: "enableDayOsd";
  } | {
    /**
     * @generated from field: cmd.OSD.DisableDayOSD disable_day_osd = 8;
     */
    value: DisableDayOSD;
    case: "disableDayOsd";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message cmd.OSD.Root.
 * Use `create(RootSchema)` to create a new message.
 */
export const RootSchema: GenMessage<Root> = /*@__PURE__*/
  messageDesc(file_jon_shared_cmd_osd, 0);

/**
 * @generated from message cmd.OSD.ShowDefaultScreen
 */
export type ShowDefaultScreen = Message<"cmd.OSD.ShowDefaultScreen"> & {
};

/**
 * Describes the message cmd.OSD.ShowDefaultScreen.
 * Use `create(ShowDefaultScreenSchema)` to create a new message.
 */
export const ShowDefaultScreenSchema: GenMessage<ShowDefaultScreen> = /*@__PURE__*/
  messageDesc(file_jon_shared_cmd_osd, 1);

/**
 * @generated from message cmd.OSD.ShowLRFMeasureScreen
 */
export type ShowLRFMeasureScreen = Message<"cmd.OSD.ShowLRFMeasureScreen"> & {
};

/**
 * Describes the message cmd.OSD.ShowLRFMeasureScreen.
 * Use `create(ShowLRFMeasureScreenSchema)` to create a new message.
 */
export const ShowLRFMeasureScreenSchema: GenMessage<ShowLRFMeasureScreen> = /*@__PURE__*/
  messageDesc(file_jon_shared_cmd_osd, 2);

/**
 * @generated from message cmd.OSD.ShowLRFResultScreen
 */
export type ShowLRFResultScreen = Message<"cmd.OSD.ShowLRFResultScreen"> & {
};

/**
 * Describes the message cmd.OSD.ShowLRFResultScreen.
 * Use `create(ShowLRFResultScreenSchema)` to create a new message.
 */
export const ShowLRFResultScreenSchema: GenMessage<ShowLRFResultScreen> = /*@__PURE__*/
  messageDesc(file_jon_shared_cmd_osd, 3);

/**
 * @generated from message cmd.OSD.ShowLRFResultSimplifiedScreen
 */
export type ShowLRFResultSimplifiedScreen = Message<"cmd.OSD.ShowLRFResultSimplifiedScreen"> & {
};

/**
 * Describes the message cmd.OSD.ShowLRFResultSimplifiedScreen.
 * Use `create(ShowLRFResultSimplifiedScreenSchema)` to create a new message.
 */
export const ShowLRFResultSimplifiedScreenSchema: GenMessage<ShowLRFResultSimplifiedScreen> = /*@__PURE__*/
  messageDesc(file_jon_shared_cmd_osd, 4);

/**
 * @generated from message cmd.OSD.EnableHeatOSD
 */
export type EnableHeatOSD = Message<"cmd.OSD.EnableHeatOSD"> & {
};

/**
 * Describes the message cmd.OSD.EnableHeatOSD.
 * Use `create(EnableHeatOSDSchema)` to create a new message.
 */
export const EnableHeatOSDSchema: GenMessage<EnableHeatOSD> = /*@__PURE__*/
  messageDesc(file_jon_shared_cmd_osd, 5);

/**
 * @generated from message cmd.OSD.DisableHeatOSD
 */
export type DisableHeatOSD = Message<"cmd.OSD.DisableHeatOSD"> & {
};

/**
 * Describes the message cmd.OSD.DisableHeatOSD.
 * Use `create(DisableHeatOSDSchema)` to create a new message.
 */
export const DisableHeatOSDSchema: GenMessage<DisableHeatOSD> = /*@__PURE__*/
  messageDesc(file_jon_shared_cmd_osd, 6);

/**
 * @generated from message cmd.OSD.EnableDayOSD
 */
export type EnableDayOSD = Message<"cmd.OSD.EnableDayOSD"> & {
};

/**
 * Describes the message cmd.OSD.EnableDayOSD.
 * Use `create(EnableDayOSDSchema)` to create a new message.
 */
export const EnableDayOSDSchema: GenMessage<EnableDayOSD> = /*@__PURE__*/
  messageDesc(file_jon_shared_cmd_osd, 7);

/**
 * @generated from message cmd.OSD.DisableDayOSD
 */
export type DisableDayOSD = Message<"cmd.OSD.DisableDayOSD"> & {
};

/**
 * Describes the message cmd.OSD.DisableDayOSD.
 * Use `create(DisableDayOSDSchema)` to create a new message.
 */
export const DisableDayOSDSchema: GenMessage<DisableDayOSD> = /*@__PURE__*/
  messageDesc(file_jon_shared_cmd_osd, 8);

