// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file jon_shared_data_pmu.proto (package ser, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "./buf/validate/validate_pb";
import type { JonGuiDataMeteo } from "./jon_shared_data_types_pb";
import { file_jon_shared_data_types } from "./jon_shared_data_types_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file jon_shared_data_pmu.proto.
 */
export const file_jon_shared_data_pmu: GenFile = /*@__PURE__*/
  fileDesc("Chlqb25fc2hhcmVkX2RhdGFfcG11LnByb3RvEgNzZXIioAMKDUpvbkd1aURhdGFQTVUSUAoLdGVtcGVyYXR1cmUYASABKAFCO7pIOBI2GcP1KFyPooRAKWZmZmZmEnHASQAAAAAAADTASQAAAAAAAAAASQAAAAAAADlASQAAAAAAAFlAEhIKCmlzX3N0YXJ0ZWQYAyABKAgSIwoFbWV0ZW8YBCABKAsyFC5zZXIuSm9uR3VpRGF0YU1ldGVvEigKB3ZvbHRhZ2UYBSABKAFCF7pIFBISGQAAAAAAAE5AKQAAAAAAAABAEhoKEmhlYXRlcl9wb3dlcl9zdGF0ZRgGIAEoCBIsCgtpbmFfdm9sdGFnZRgHIAEoAUIXukgUEhIZAAAAAAAAQkApAAAAAAAAAAASLAoLaW5hX2N1cnJlbnQYCCABKAFCF7pIFBISGQAAAAAAiMNAKQAAAAAAiMPAEioKCWluYV9wb3dlchgJIAEoAUIXukgUEhIZAAAAAABqCEEpAAAAAAAAAAASFwoPaW5hX3Bvd2VyX2ZhdWx0GAogASgIEhcKD2NoYXJnZV9kaXNhYmxlZBgLIAEoCEoECAIQA0JLWklnaXQtY29kZWNvbW1pdC5ldS1jZW50cmFsLTEuYW1hem9uYXdzLmNvbS92MS9yZXBvcy9qZXR0aXNvbi9qb25wL2RhdGEvcG11YgZwcm90bzM", [file_buf_validate_validate, file_jon_shared_data_types]);

/**
 * @generated from message ser.JonGuiDataPMU
 */
export type JonGuiDataPMU = Message<"ser.JonGuiDataPMU"> & {
  /**
   * @generated from field: double temperature = 1;
   */
  temperature: number;

  /**
   * @generated from field: bool is_started = 3;
   */
  isStarted: boolean;

  /**
   * @generated from field: ser.JonGuiDataMeteo meteo = 4;
   */
  meteo?: JonGuiDataMeteo;

  /**
   * @generated from field: double voltage = 5;
   */
  voltage: number;

  /**
   * @generated from field: bool heater_power_state = 6;
   */
  heaterPowerState: boolean;

  /**
   * INA236 power monitor
   *
   * @generated from field: double ina_voltage = 7;
   */
  inaVoltage: number;

  /**
   * @generated from field: double ina_current = 8;
   */
  inaCurrent: number;

  /**
   * @generated from field: double ina_power = 9;
   */
  inaPower: number;

  /**
   * @generated from field: bool ina_power_fault = 10;
   */
  inaPowerFault: boolean;

  /**
   * Battery charging status (false = charging enabled by default)
   *
   * @generated from field: bool charge_disabled = 11;
   */
  chargeDisabled: boolean;
};

/**
 * Describes the message ser.JonGuiDataPMU.
 * Use `create(JonGuiDataPMUSchema)` to create a new message.
 */
export const JonGuiDataPMUSchema: GenMessage<JonGuiDataPMU> = /*@__PURE__*/
  messageDesc(file_jon_shared_data_pmu, 0);

