// @generated by protoc-gen-es v2.13.0 with parameter "target=ts"
// @generated from file jon_shared_data_camera_heat.proto (package ser, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "./buf/validate/validate_pb";
import type { JonGuiDataFxModeHeat, JonGuiDataMeteo, JonGuiDataVideoChannelHeatAGCModes, JonGuiDataVideoChannelHeatFilters } from "./jon_shared_data_types_pb";
import { file_jon_shared_data_types } from "./jon_shared_data_types_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file jon_shared_data_camera_heat.proto.
 */
export const file_jon_shared_data_camera_heat: GenFile = /*@__PURE__*/
  fileDesc("CiFqb25fc2hhcmVkX2RhdGFfY2FtZXJhX2hlYXQucHJvdG8SA3NlciKpBgoUSm9uR3VpRGF0YUNhbWVyYUhlYXQSKQoIem9vbV9wb3MYASABKAFCF7pIFBISGQAAAAAAAPA/KQAAAAAAAAAAEkUKCGFnY19tb2RlGAIgASgOMicuc2VyLkpvbkd1aURhdGFWaWRlb0NoYW5uZWxIZWF0QUdDTW9kZXNCCrpIB4IBBBABIAASQgoGZmlsdGVyGAMgASgOMiYuc2VyLkpvbkd1aURhdGFWaWRlb0NoYW5uZWxIZWF0RmlsdGVyc0IKukgHggEEEAEgABISCgphdXRvX2ZvY3VzGAQgASgIEh8KDnpvb21fdGFibGVfcG9zGAUgASgFQge6SAQaAigAEiMKEnpvb21fdGFibGVfcG9zX21heBgGIAEoBUIHukgEGgIoABIdCglkZGVfbGV2ZWwYByABKAVCCrpIBxoFGIAEKAASEwoLZGRlX2VuYWJsZWQYCCABKAgSNAoHZnhfbW9kZRgJIAEoDjIZLnNlci5Kb25HdWlEYXRhRnhNb2RlSGVhdEIIukgFggECEAESKgoSZGlnaXRhbF96b29tX2xldmVsGAogASgBQg66SAsSCSkAAAAAAADwPxIsCgtjbGFoZV9sZXZlbBgLIAEoAUIXukgUEhIZAAAAAAAA8D8pAAAAAAAAAAASNwoWaG9yaXpvbnRhbF9mb3ZfZGVncmVlcxgMIAEoAUIXukgUEhIRAAAAAACAdkApAAAAAAAAAAASNQoUdmVydGljYWxfZm92X2RlZ3JlZXMYDSABKAFCF7pIFBISEQAAAAAAgHZAKQAAAAAAAAAAEhIKCmlzX3N0YXJ0ZWQYDiABKAgSIwoFbWV0ZW8YDyABKAsyFC5zZXIuSm9uR3VpRGF0YU1ldGVvEhwKFGNhcHR1cmVfbW9ub3RvbmljX3VzGBAgASgEEioKDWRlbGl2ZXJlZF9mcHMYESABKAFCDrpICxIJKQAAAAAAAAAASACIAQESKAoLY29udGVudF9mcHMYEiABKAFCDrpICxIJKQAAAAAAAAAASAGIAQFCEAoOX2RlbGl2ZXJlZF9mcHNCDgoMX2NvbnRlbnRfZnBzQlNaUWdpdC1jb2RlY29tbWl0LmV1LWNlbnRyYWwtMS5hbWF6b25hd3MuY29tL3YxL3JlcG9zL2pldHRpc29uL2pvbnAvZGF0YS9jYW1lcmFfaGVhdGIGcHJvdG8z", [file_buf_validate_validate, file_jon_shared_data_types]);

/**
 * @generated from message ser.JonGuiDataCameraHeat
 */
export type JonGuiDataCameraHeat = Message<"ser.JonGuiDataCameraHeat"> & {
  /**
   * @generated from field: double zoom_pos = 1;
   */
  zoomPos: number;

  /**
   * @generated from field: ser.JonGuiDataVideoChannelHeatAGCModes agc_mode = 2;
   */
  agcMode: JonGuiDataVideoChannelHeatAGCModes;

  /**
   * @generated from field: ser.JonGuiDataVideoChannelHeatFilters filter = 3;
   */
  filter: JonGuiDataVideoChannelHeatFilters;

  /**
   * @generated from field: bool auto_focus = 4;
   */
  autoFocus: boolean;

  /**
   * @generated from field: int32 zoom_table_pos = 5;
   */
  zoomTablePos: number;

  /**
   * @generated from field: int32 zoom_table_pos_max = 6;
   */
  zoomTablePosMax: number;

  /**
   * @generated from field: int32 dde_level = 7;
   */
  ddeLevel: number;

  /**
   * @generated from field: bool dde_enabled = 8;
   */
  ddeEnabled: boolean;

  /**
   * @generated from field: ser.JonGuiDataFxModeHeat fx_mode = 9;
   */
  fxMode: JonGuiDataFxModeHeat;

  /**
   * @generated from field: double digital_zoom_level = 10;
   */
  digitalZoomLevel: number;

  /**
   * @generated from field: double clahe_level = 11;
   */
  claheLevel: number;

  /**
   * @generated from field: double horizontal_fov_degrees = 12;
   */
  horizontalFovDegrees: number;

  /**
   * @generated from field: double vertical_fov_degrees = 13;
   */
  verticalFovDegrees: number;

  /**
   * @generated from field: bool is_started = 14;
   */
  isStarted: boolean;

  /**
   * @generated from field: ser.JonGuiDataMeteo meteo = 15;
   */
  meteo?: JonGuiDataMeteo | undefined;

  /**
   * CLOCK_MONOTONIC timestamp (microseconds) when state was last pushed to SHM
   *
   * @generated from field: uint64 capture_monotonic_us = 16;
   */
  captureMonotonicUs: bigint;

  /**
   * Measured video rates for this channel, in frames per second. Absent until
   * the producer has two samples to difference; zero when present means
   * nothing is arriving, which is a measurement rather than an absence.
   * delivered_fps counts frames handed on, content_fps only frames whose
   * content changed.
   *
   * DIVERGENCE IS THE SIGNAL, NOT THE BASELINE. A healthy idle heat channel
   * reads the two rates EQUAL: the 2:1 ingress drop ahead of the GPU upload
   * cancels the thermal core's idle re-serve exactly. Do not read a 1:1 heat
   * channel as a broken counter. Content falls below delivery under scan
   * load, not at rest.
   *
   * @generated from field: optional double delivered_fps = 17;
   */
  deliveredFps?: number | undefined;

  /**
   * @generated from field: optional double content_fps = 18;
   */
  contentFps?: number | undefined;
};

/**
 * Describes the message ser.JonGuiDataCameraHeat.
 * Use `create(JonGuiDataCameraHeatSchema)` to create a new message.
 */
export const JonGuiDataCameraHeatSchema: GenMessage<JonGuiDataCameraHeat> = /*@__PURE__*/
  messageDesc(file_jon_shared_data_camera_heat, 0);

