// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file jon_shared_data_cv.proto (package ser, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "./buf/validate/validate_pb";
import { file_jon_shared_data_types } from "./jon_shared_data_types_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file jon_shared_data_cv.proto.
 */
export const file_jon_shared_data_cv: GenFile = /*@__PURE__*/
  fileDesc("Chhqb25fc2hhcmVkX2RhdGFfY3YucHJvdG8SA3NlciLyBgoMSm9uR3VpRGF0YUNWEkcKE2F1dG9mb2N1c19zdGF0ZV9kYXkYASABKA4yIC5zZXIuSm9uR3VpRGF0YUNWLkF1dG9mb2N1c1N0YXRlQgi6SAWCAQIQARIlCg1zaGFycG5lc3NfZGF5GAIgASgBQg66SAsSCSkAAAAAAAAAABIqChJiZXN0X3NoYXJwbmVzc19kYXkYAyABKAFCDrpICxIJKQAAAAAAAAAAEiUKEnN3ZWVwX3Byb2dyZXNzX2RheRgEIAEoBUIJukgGGgQYZCgAEjMKEmJlc3RfZm9jdXNfcG9zX2RheRgFIAEoAUIXukgUEhIZAAAAAAAA8D8pAAAAAAAAAAASSAoUYXV0b2ZvY3VzX3N0YXRlX2hlYXQYCiABKA4yIC5zZXIuSm9uR3VpRGF0YUNWLkF1dG9mb2N1c1N0YXRlQgi6SAWCAQIQARImCg5zaGFycG5lc3NfaGVhdBgLIAEoAUIOukgLEgkpAAAAAAAAAAASKwoTYmVzdF9zaGFycG5lc3NfaGVhdBgMIAEoAUIOukgLEgkpAAAAAAAAAAASJgoTc3dlZXBfcHJvZ3Jlc3NfaGVhdBgNIAEoBUIJukgGGgQYZCgAEjQKE2Jlc3RfZm9jdXNfcG9zX2hlYXQYDiABKAFCF7pIFBISGQAAAAAAAPA/KQAAAAAAAAAAEicKBnJvaV94MRgUIAEoAUIXukgUEhIZAAAAAAAA8D8pAAAAAAAA8L8SJwoGcm9pX3kxGBUgASgBQhe6SBQSEhkAAAAAAADwPykAAAAAAADwvxInCgZyb2lfeDIYFiABKAFCF7pIFBISGQAAAAAAAPA/KQAAAAAAAPC/EicKBnJvaV95MhgXIAEoAUIXukgUEhIZAAAAAAAA8D8pAAAAAAAA8L8iyAEKDkF1dG9mb2N1c1N0YXRlEh8KG0FVVE9GT0NVU19TVEFURV9VTlNQRUNJRklFRBAAEhgKFEFVVE9GT0NVU19TVEFURV9JRExFEAESIAocQVVUT0ZPQ1VTX1NUQVRFX0NPQVJTRV9TV0VFUBACEh4KGkFVVE9GT0NVU19TVEFURV9GSU5FX1NXRUVQEAMSHQoZQVVUT0ZPQ1VTX1NUQVRFX0NPTlZFUkdFRBAEEhoKFkFVVE9GT0NVU19TVEFURV9GQUlMRUQQBUJKWkhnaXQtY29kZWNvbW1pdC5ldS1jZW50cmFsLTEuYW1hem9uYXdzLmNvbS92MS9yZXBvcy9qZXR0aXNvbi9qb25wL2RhdGEvY3ZiBnByb3RvMw", [file_buf_validate_validate, file_jon_shared_data_types]);

/**
 * CV Gateway state enrichment - autofocus metrics and sweep status
 *
 * @generated from message ser.JonGuiDataCV
 */
export type JonGuiDataCV = Message<"ser.JonGuiDataCV"> & {
  /**
   * Day channel autofocus
   *
   * @generated from field: ser.JonGuiDataCV.AutofocusState autofocus_state_day = 1;
   */
  autofocusStateDay: JonGuiDataCV_AutofocusState;

  /**
   * @generated from field: double sharpness_day = 2;
   */
  sharpnessDay: number;

  /**
   * @generated from field: double best_sharpness_day = 3;
   */
  bestSharpnessDay: number;

  /**
   * @generated from field: int32 sweep_progress_day = 4;
   */
  sweepProgressDay: number;

  /**
   * @generated from field: double best_focus_pos_day = 5;
   */
  bestFocusPosDay: number;

  /**
   * Heat channel autofocus
   *
   * @generated from field: ser.JonGuiDataCV.AutofocusState autofocus_state_heat = 10;
   */
  autofocusStateHeat: JonGuiDataCV_AutofocusState;

  /**
   * @generated from field: double sharpness_heat = 11;
   */
  sharpnessHeat: number;

  /**
   * @generated from field: double best_sharpness_heat = 12;
   */
  bestSharpnessHeat: number;

  /**
   * @generated from field: int32 sweep_progress_heat = 13;
   */
  sweepProgressHeat: number;

  /**
   * @generated from field: double best_focus_pos_heat = 14;
   */
  bestFocusPosHeat: number;

  /**
   * ROI for sharpness calculation (NDC coords: -1 to 1)
   *
   * @generated from field: double roi_x1 = 20;
   */
  roiX1: number;

  /**
   * @generated from field: double roi_y1 = 21;
   */
  roiY1: number;

  /**
   * @generated from field: double roi_x2 = 22;
   */
  roiX2: number;

  /**
   * @generated from field: double roi_y2 = 23;
   */
  roiY2: number;
};

/**
 * Describes the message ser.JonGuiDataCV.
 * Use `create(JonGuiDataCVSchema)` to create a new message.
 */
export const JonGuiDataCVSchema: GenMessage<JonGuiDataCV> = /*@__PURE__*/
  messageDesc(file_jon_shared_data_cv, 0);

/**
 * Autofocus sweep state
 *
 * @generated from enum ser.JonGuiDataCV.AutofocusState
 */
export enum JonGuiDataCV_AutofocusState {
  /**
   * @generated from enum value: AUTOFOCUS_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: AUTOFOCUS_STATE_IDLE = 1;
   */
  IDLE = 1,

  /**
   * @generated from enum value: AUTOFOCUS_STATE_COARSE_SWEEP = 2;
   */
  COARSE_SWEEP = 2,

  /**
   * @generated from enum value: AUTOFOCUS_STATE_FINE_SWEEP = 3;
   */
  FINE_SWEEP = 3,

  /**
   * @generated from enum value: AUTOFOCUS_STATE_CONVERGED = 4;
   */
  CONVERGED = 4,

  /**
   * @generated from enum value: AUTOFOCUS_STATE_FAILED = 5;
   */
  FAILED = 5,
}

/**
 * Describes the enum ser.JonGuiDataCV.AutofocusState.
 */
export const JonGuiDataCV_AutofocusStateSchema: GenEnum<JonGuiDataCV_AutofocusState> = /*@__PURE__*/
  enumDesc(file_jon_shared_data_cv, 0, 0);

