// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file jon_client_logs.proto (package jon.logs, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "./buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file jon_client_logs.proto.
 */
export const file_jon_client_logs: GenFile = /*@__PURE__*/
  fileDesc("ChVqb25fY2xpZW50X2xvZ3MucHJvdG8SCGpvbi5sb2dzIqYDCg5DbGllbnRMb2dFbnRyeRIsCgNsdmwYASABKAlCH7pIHHIaUgVlcnJvclIEd2FyblIEaW5mb1IFZGVidWcSFAoDbW9kGAIgASgJQge6SARyAhABEhQKA21zZxgDIAEoCUIHukgEcgIQARITCgJ0cxgEIAEoA0IHukgEIgIoABIMCgRmaWxlGAUgASgJEgwKBGxpbmUYBiABKAUSFAoDc2lkGAcgASgJQge6SARyAhABEgoKAnVhGAggASgJEhAKA3VybBgJIAEoCUgAiAEBEhMKBm9yaWdpbhgKIAEoCUgBiAEBEg4KBmNvbW1pdBgLIAEoCRINCgVidWlsZBgMIAEoCRITCgJzdxgNIAEoBUIHukgEGgIoABITCgJzaBgOIAEoBUIHukgEGgIoABILCgNkcHIYDyABKAESDAoEbGFuZxgQIAEoCRIKCgJ0ehgRIAEoCRINCgVleHRyYRgSIAEoCRIbCg5zdGF0ZV9zbmFwc2hvdBgTIAEoDEgCiAEBQgYKBF91cmxCCQoHX29yaWdpbkIRCg9fc3RhdGVfc25hcHNob3QiYQoOQ2xpZW50TG9nQmF0Y2gSGgoHdmVyc2lvbhgBIAEoDUIJukgGKgQYASgBEjMKB2VudHJpZXMYAiADKAsyGC5qb24ubG9ncy5DbGllbnRMb2dFbnRyeUIIukgFkgECCAFCR1pFZ2l0LWNvZGVjb21taXQuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb20vdjEvcmVwb3MvamV0dGlzb24vam9ucC9sb2dzYgZwcm90bzM", [file_buf_validate_validate]);

/**
 * Client log entry - represents a single log message from the frontend
 *
 * @generated from message jon.logs.ClientLogEntry
 */
export type ClientLogEntry = Message<"jon.logs.ClientLogEntry"> & {
  /**
   * Core log data (validated on ingress)
   *
   * @generated from field: string lvl = 1;
   */
  lvl: string;

  /**
   * @generated from field: string mod = 2;
   */
  mod: string;

  /**
   * @generated from field: string msg = 3;
   */
  msg: string;

  /**
   * @generated from field: int64 ts = 4;
   */
  ts: bigint;

  /**
   * Source location
   *
   * @generated from field: string file = 5;
   */
  file: string;

  /**
   * @generated from field: int32 line = 6;
   */
  line: number;

  /**
   * Session/client info
   *
   * @generated from field: string sid = 7;
   */
  sid: string;

  /**
   * user agent
   *
   * @generated from field: string ua = 8;
   */
  ua: string;

  /**
   * page path + query (optional - workers don't have location)
   *
   * @generated from field: optional string url = 9;
   */
  url?: string;

  /**
   * page origin (optional - workers don't have location)
   *
   * @generated from field: optional string origin = 10;
   */
  origin?: string;

  /**
   * git commit hash (build-time)
   *
   * @generated from field: string commit = 11;
   */
  commit: string;

  /**
   * build timestamp
   *
   * @generated from field: string build = 12;
   */
  build: string;

  /**
   * Device info
   *
   * @generated from field: int32 sw = 13;
   */
  sw: number;

  /**
   * @generated from field: int32 sh = 14;
   */
  sh: number;

  /**
   * device pixel ratio
   *
   * @generated from field: double dpr = 15;
   */
  dpr: number;

  /**
   * browser language
   *
   * @generated from field: string lang = 16;
   */
  lang: string;

  /**
   * timezone
   *
   * @generated from field: string tz = 17;
   */
  tz: string;

  /**
   * optional JSON blob
   *
   * @generated from field: string extra = 18;
   */
  extra: string;

  /**
   * Raw state snapshot bytes - NOT validated, stored as-is, decode later
   *
   * @generated from field: optional bytes state_snapshot = 19;
   */
  stateSnapshot?: Uint8Array;
};

/**
 * Describes the message jon.logs.ClientLogEntry.
 * Use `create(ClientLogEntrySchema)` to create a new message.
 */
export const ClientLogEntrySchema: GenMessage<ClientLogEntry> = /*@__PURE__*/
  messageDesc(file_jon_client_logs, 0);

/**
 * Batch of client log entries - sent over WebSocket
 *
 * @generated from message jon.logs.ClientLogBatch
 */
export type ClientLogBatch = Message<"jon.logs.ClientLogBatch"> & {
  /**
   * Protocol version for future compatibility
   *
   * Currently only v1
   *
   * @generated from field: uint32 version = 1;
   */
  version: number;

  /**
   * @generated from field: repeated jon.logs.ClientLogEntry entries = 2;
   */
  entries: ClientLogEntry[];
};

/**
 * Describes the message jon.logs.ClientLogBatch.
 * Use `create(ClientLogBatchSchema)` to create a new message.
 */
export const ClientLogBatchSchema: GenMessage<ClientLogBatch> = /*@__PURE__*/
  messageDesc(file_jon_client_logs, 1);

