// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file jon_shared_data.proto (package ser, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "./buf/validate/validate_pb";
import type { JonGuiDataMeteo, JonGuiDataStateSource } from "./jon_shared_data_types_pb";
import { file_jon_shared_data_types } from "./jon_shared_data_types_pb";
import type { JonGuiDataTime } from "./jon_shared_data_time_pb";
import { file_jon_shared_data_time } from "./jon_shared_data_time_pb";
import type { JonGuiDataSystem } from "./jon_shared_data_system_pb";
import { file_jon_shared_data_system } from "./jon_shared_data_system_pb";
import type { JonGuiDataLrf } from "./jon_shared_data_lrf_pb";
import { file_jon_shared_data_lrf } from "./jon_shared_data_lrf_pb";
import type { JonGuiDataGps } from "./jon_shared_data_gps_pb";
import { file_jon_shared_data_gps } from "./jon_shared_data_gps_pb";
import type { JonGuiDataCompass } from "./jon_shared_data_compass_pb";
import { file_jon_shared_data_compass } from "./jon_shared_data_compass_pb";
import type { JonGuiDataCompassCalibration } from "./jon_shared_data_compass_calibration_pb";
import { file_jon_shared_data_compass_calibration } from "./jon_shared_data_compass_calibration_pb";
import type { JonGuiDataRotary } from "./jon_shared_data_rotary_pb";
import { file_jon_shared_data_rotary } from "./jon_shared_data_rotary_pb";
import type { JonGuiDataCameraDay } from "./jon_shared_data_camera_day_pb";
import { file_jon_shared_data_camera_day } from "./jon_shared_data_camera_day_pb";
import type { JonGuiDataCameraHeat } from "./jon_shared_data_camera_heat_pb";
import { file_jon_shared_data_camera_heat } from "./jon_shared_data_camera_heat_pb";
import type { JonGuiDataRecOsd } from "./jon_shared_data_rec_osd_pb";
import { file_jon_shared_data_rec_osd } from "./jon_shared_data_rec_osd_pb";
import type { JonGuiDataDayCamGlassHeater } from "./jon_shared_data_day_cam_glass_heater_pb";
import { file_jon_shared_data_day_cam_glass_heater } from "./jon_shared_data_day_cam_glass_heater_pb";
import type { JonGuiDataActualSpaceTime } from "./jon_shared_data_actual_space_time_pb";
import { file_jon_shared_data_actual_space_time } from "./jon_shared_data_actual_space_time_pb";
import type { JonGuiDataPower } from "./jon_shared_data_power_pb";
import { file_jon_shared_data_power } from "./jon_shared_data_power_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file jon_shared_data.proto.
 */
export const file_jon_shared_data: GenFile = /*@__PURE__*/
  fileDesc("ChVqb25fc2hhcmVkX2RhdGEucHJvdG8SA3NlciLwBwoLSm9uR1VJU3RhdGUSJwoQcHJvdG9jb2xfdmVyc2lvbhgBIAEoDUINukgKKggY/////wcgABIpChhzeXN0ZW1fbW9ub3RvbmljX3RpbWVfdXMYAiABKARCB7pIBDICKAASPAoMc3RhdGVfc291cmNlGAMgASgOMhouc2VyLkpvbkd1aURhdGFTdGF0ZVNvdXJjZUIKukgHggEEEAEgABIhChBmcmFtZV9wdHNfZGF5X25zGAQgASgEQge6SAQyAigAEiIKEWZyYW1lX3B0c19oZWF0X25zGAUgASgEQge6SAQyAigAEi0KBnN5c3RlbRgNIAEoCzIVLnNlci5Kb25HdWlEYXRhU3lzdGVtQga6SAPIAQESNAoObWV0ZW9faW50ZXJuYWwYDiABKAsyFC5zZXIuSm9uR3VpRGF0YU1ldGVvQga6SAPIAQESJwoDbHJmGA8gASgLMhIuc2VyLkpvbkd1aURhdGFMcmZCBrpIA8gBARIpCgR0aW1lGBAgASgLMhMuc2VyLkpvbkd1aURhdGFUaW1lQga6SAPIAQESJwoDZ3BzGBEgASgLMhIuc2VyLkpvbkd1aURhdGFHcHNCBrpIA8gBARIvCgdjb21wYXNzGBIgASgLMhYuc2VyLkpvbkd1aURhdGFDb21wYXNzQga6SAPIAQESLQoGcm90YXJ5GBMgASgLMhUuc2VyLkpvbkd1aURhdGFSb3RhcnlCBrpIA8gBARI0CgpjYW1lcmFfZGF5GBQgASgLMhguc2VyLkpvbkd1aURhdGFDYW1lcmFEYXlCBrpIA8gBARI2CgtjYW1lcmFfaGVhdBgVIAEoCzIZLnNlci5Kb25HdWlEYXRhQ2FtZXJhSGVhdEIGukgDyAEBEkYKE2NvbXBhc3NfY2FsaWJyYXRpb24YFiABKAsyIS5zZXIuSm9uR3VpRGF0YUNvbXBhc3NDYWxpYnJhdGlvbkIGukgDyAEBEi4KB3JlY19vc2QYFyABKAsyFS5zZXIuSm9uR3VpRGF0YVJlY09zZEIGukgDyAEBEkYKFGRheV9jYW1fZ2xhc3NfaGVhdGVyGBggASgLMiAuc2VyLkpvbkd1aURhdGFEYXlDYW1HbGFzc0hlYXRlckIGukgDyAEBEkEKEWFjdHVhbF9zcGFjZV90aW1lGBkgASgLMh4uc2VyLkpvbkd1aURhdGFBY3R1YWxTcGFjZVRpbWVCBrpIA8gBARIrCgVwb3dlchgaIAEoCzIULnNlci5Kb25HdWlEYXRhUG93ZXJCBrpIA8gBAUoECAYQB0oECAcQCEoECAgQCUoECAkQCkoECAoQC0oECAsQDEoECAwQDUJHWkVnaXQtY29kZWNvbW1pdC5ldS1jZW50cmFsLTEuYW1hem9uYXdzLmNvbS92MS9yZXBvcy9qZXR0aXNvbi9qb25wL2RhdGFiBnByb3RvMw", [file_buf_validate_validate, file_jon_shared_data_types, file_jon_shared_data_time, file_jon_shared_data_system, file_jon_shared_data_lrf, file_jon_shared_data_gps, file_jon_shared_data_compass, file_jon_shared_data_compass_calibration, file_jon_shared_data_rotary, file_jon_shared_data_camera_day, file_jon_shared_data_camera_heat, file_jon_shared_data_rec_osd, file_jon_shared_data_day_cam_glass_heater, file_jon_shared_data_actual_space_time, file_jon_shared_data_power]);

/**
 * Root message
 *
 * @generated from message ser.JonGUIState
 */
export type JonGUIState = Message<"ser.JonGUIState"> & {
  /**
   * @generated from field: uint32 protocol_version = 1;
   */
  protocolVersion: number;

  /**
   * System monotonic time in microseconds
   *
   * @generated from field: uint64 system_monotonic_time_us = 2;
   */
  systemMonotonicTimeUs: bigint;

  /**
   * @generated from field: ser.JonGuiDataStateSource state_source = 3;
   */
  stateSource: JonGuiDataStateSource;

  /**
   * Day pipeline GStreamer buffer PTS in nanoseconds
   *
   * @generated from field: uint64 frame_pts_day_ns = 4;
   */
  framePtsDayNs: bigint;

  /**
   * Heat pipeline GStreamer buffer PTS in nanoseconds
   *
   * @generated from field: uint64 frame_pts_heat_ns = 5;
   */
  framePtsHeatNs: bigint;

  /**
   * @generated from field: ser.JonGuiDataSystem system = 13;
   */
  system?: JonGuiDataSystem;

  /**
   * @generated from field: ser.JonGuiDataMeteo meteo_internal = 14;
   */
  meteoInternal?: JonGuiDataMeteo;

  /**
   * @generated from field: ser.JonGuiDataLrf lrf = 15;
   */
  lrf?: JonGuiDataLrf;

  /**
   * @generated from field: ser.JonGuiDataTime time = 16;
   */
  time?: JonGuiDataTime;

  /**
   * @generated from field: ser.JonGuiDataGps gps = 17;
   */
  gps?: JonGuiDataGps;

  /**
   * @generated from field: ser.JonGuiDataCompass compass = 18;
   */
  compass?: JonGuiDataCompass;

  /**
   * @generated from field: ser.JonGuiDataRotary rotary = 19;
   */
  rotary?: JonGuiDataRotary;

  /**
   * @generated from field: ser.JonGuiDataCameraDay camera_day = 20;
   */
  cameraDay?: JonGuiDataCameraDay;

  /**
   * @generated from field: ser.JonGuiDataCameraHeat camera_heat = 21;
   */
  cameraHeat?: JonGuiDataCameraHeat;

  /**
   * @generated from field: ser.JonGuiDataCompassCalibration compass_calibration = 22;
   */
  compassCalibration?: JonGuiDataCompassCalibration;

  /**
   * @generated from field: ser.JonGuiDataRecOsd rec_osd = 23;
   */
  recOsd?: JonGuiDataRecOsd;

  /**
   * @generated from field: ser.JonGuiDataDayCamGlassHeater day_cam_glass_heater = 24;
   */
  dayCamGlassHeater?: JonGuiDataDayCamGlassHeater;

  /**
   * @generated from field: ser.JonGuiDataActualSpaceTime actual_space_time = 25;
   */
  actualSpaceTime?: JonGuiDataActualSpaceTime;

  /**
   * @generated from field: ser.JonGuiDataPower power = 26;
   */
  power?: JonGuiDataPower;
};

/**
 * Describes the message ser.JonGUIState.
 * Use `create(JonGUIStateSchema)` to create a new message.
 */
export const JonGUIStateSchema: GenMessage<JonGUIState> = /*@__PURE__*/
  messageDesc(file_jon_shared_data, 0);

