// @generated by protoc-gen-es v2.13.0 with parameter "target=ts"
// @generated from file opaque/cv_meta.proto (package ser, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../buf/validate/validate_pb";
import type { JonGuiDataCameraDay } from "../jon_shared_data_camera_day_pb";
import { file_jon_shared_data_camera_day } from "../jon_shared_data_camera_day_pb";
import type { JonGuiDataCameraHeat } from "../jon_shared_data_camera_heat_pb";
import { file_jon_shared_data_camera_heat } from "../jon_shared_data_camera_heat_pb";
import type { JonGuiDataRotary } from "../jon_shared_data_rotary_pb";
import { file_jon_shared_data_rotary } from "../jon_shared_data_rotary_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file opaque/cv_meta.proto.
 */
export const file_opaque_cv_meta: GenFile = /*@__PURE__*/
  fileDesc("ChRvcGFxdWUvY3ZfbWV0YS5wcm90bxIDc2VyIrwDCg1DdkNoYW5uZWxNZXRhEhcKBnB0c19ucxgBIAEoBEIHukgEMgIoABIgCg9jYXB0dXJlX3RpbWVfbnMYAiABKARCB7pIBDICKAASEgoKZ2VuZXJhdGlvbhgDIAEoDRIpChBzaGFycG5lc3NfbGV2ZWwwGAQgASgCQg+6SAwKCh0AAIA/LQAAAAASJAoQc2hhcnBuZXNzX2xldmVsMRgFIAMoAkIKukgHkgEECAQQBBIkChBzaGFycG5lc3NfbGV2ZWwyGAYgAygCQgq6SAeSAQQIEBAQEiYKEHNoYXJwbmVzc19sZXZlbDMYByADKAJCDLpICZIBBgigARCgARIlChRzaGFycG5lc3NfY29tcHV0ZV9ucxgIIAEoBEIHukgEMgIoABIjChJzaGFycG5lc3NfdG90YWxfbnMYCSABKARCB7pIBDICKAASFwoPc2hhcnBuZXNzX3ZhbGlkGAogASgIEhMKC3NlbnNvcl9nYWluGAsgASgFEhIKCmdhaW5fdmFsaWQYDCABKAgSFwoPc2Vuc29yX2V4cG9zdXJlGA0gASgFEhYKDmV4cG9zdXJlX3ZhbGlkGA4gASgIIqsCCgZDdk1ldGESJQoUY2FwdHVyZV9tb25vdG9uaWNfdXMYASABKARCB7pIBDICKAASIgoPdXBkYXRlZF9zb3VyY2VzGAIgASgNQgm6SAYqBBgfKAASLAoKY2FtZXJhX2RheRgDIAEoCzIYLnNlci5Kb25HdWlEYXRhQ2FtZXJhRGF5Ei4KC2NhbWVyYV9oZWF0GAQgASgLMhkuc2VyLkpvbkd1aURhdGFDYW1lcmFIZWF0EiUKBnJvdGFyeRgFIAEoCzIVLnNlci5Kb25HdWlEYXRhUm90YXJ5EicKC2NoYW5uZWxfZGF5GAYgASgLMhIuc2VyLkN2Q2hhbm5lbE1ldGESKAoMY2hhbm5lbF9oZWF0GAcgASgLMhIuc2VyLkN2Q2hhbm5lbE1ldGFCSVpHZ2l0LWNvZGVjb21taXQuZXUtY2VudHJhbC0xLmFtYXpvbmF3cy5jb20vdjEvcmVwb3MvamV0dGlzb24vam9ucC9vcGFxdWViBnByb3RvMw", [file_buf_validate_validate, file_jon_shared_data_camera_day, file_jon_shared_data_camera_heat, file_jon_shared_data_rotary]);

/**
 * Per-channel CUDA IPC metadata (frame timing + sharpness pyramid + sensor gain).
 * Populated from /jon_cuda_ipc_day and /jon_cuda_ipc_heat shared memory.
 *
 * @generated from message ser.CvChannelMeta
 */
export type CvChannelMeta = Message<"ser.CvChannelMeta"> & {
  /**
   * Frame timing (nanoseconds, must be non-negative)
   *
   * @generated from field: uint64 pts_ns = 1;
   */
  ptsNs: bigint;

  /**
   * @generated from field: uint64 capture_time_ns = 2;
   */
  captureTimeNs: bigint;

  /**
   * @generated from field: uint32 generation = 3;
   */
  generation: number;

  /**
   * Sharpness pyramid (85 floats total, all normalized 0.0-1.0)
   * Global sharpness score
   *
   * @generated from field: float sharpness_level0 = 4;
   */
  sharpnessLevel0: number;

  /**
   * Quadrants: TL, TR, BL, BR (exactly 4 elements)
   *
   * @generated from field: repeated float sharpness_level1 = 5;
   */
  sharpnessLevel1: number[];

  /**
   * 4x4 grid (exactly 16 elements, row-major)
   *
   * @generated from field: repeated float sharpness_level2 = 6;
   */
  sharpnessLevel2: number[];

  /**
   * 16x10 grid (exactly 160 elements, row-major)
   *
   * @generated from field: repeated float sharpness_level3 = 7;
   */
  sharpnessLevel3: number[];

  /**
   * Timing metrics (nanoseconds)
   *
   * @generated from field: uint64 sharpness_compute_ns = 8;
   */
  sharpnessComputeNs: bigint;

  /**
   * @generated from field: uint64 sharpness_total_ns = 9;
   */
  sharpnessTotalNs: bigint;

  /**
   * @generated from field: bool sharpness_valid = 10;
   */
  sharpnessValid: boolean;

  /**
   * Sensor gain (day camera only; heat channel sets gain_valid=false)
   *
   * @generated from field: int32 sensor_gain = 11;
   */
  sensorGain: number;

  /**
   * @generated from field: bool gain_valid = 12;
   */
  gainValid: boolean;

  /**
   * Sensor exposure (day camera only; heat channel sets exposure_valid=false)
   * IMX290 range: 15-16820
   *
   * @generated from field: int32 sensor_exposure = 13;
   */
  sensorExposure: number;

  /**
   * @generated from field: bool exposure_valid = 14;
   */
  exposureValid: boolean;
};

/**
 * Describes the message ser.CvChannelMeta.
 * Use `create(CvChannelMetaSchema)` to create a new message.
 */
export const CvChannelMetaSchema: GenMessage<CvChannelMeta> = /*@__PURE__*/
  messageDesc(file_opaque_cv_meta, 0);

/**
 * Aggregated CV metadata payload - combines all SHM sources at 60fps.
 * Injected by cv-gateway into JonGUIState.opaque_payloads.
 *
 * Sources:
 * - /jon_shm_rotary (rotary turret state)
 * - /jon_shm_cam_day (day camera settings)
 * - /jon_shm_cam_heat (thermal camera settings)
 * - /jon_cuda_ipc_day (day channel CUDA IPC metadata)
 * - /jon_cuda_ipc_heat (heat channel CUDA IPC metadata)
 *
 * UUID: 019c3e33-d52d-7552-b36b-6fdcaa5d59b8
 *
 * @generated from message ser.CvMeta
 */
export type CvMeta = Message<"ser.CvMeta"> & {
  /**
   * Correlation timestamp (CLOCK_MONOTONIC, microseconds)
   *
   * @generated from field: uint64 capture_monotonic_us = 1;
   */
  captureMonotonicUs: bigint;

  /**
   * Freshness bitmask indicating which sources updated since last publish
   * Bits: 0=rotary, 1=cam_day, 2=cam_heat, 3=cuda_day, 4=cuda_heat
   * Valid range: 0-31 (5 bits)
   *
   * @generated from field: uint32 updated_sources = 2;
   */
  updatedSources: number;

  /**
   * Embedded state messages (full copies from SHMs)
   * These are validated by their own proto definitions
   *
   * @generated from field: ser.JonGuiDataCameraDay camera_day = 3;
   */
  cameraDay?: JonGuiDataCameraDay | undefined;

  /**
   * @generated from field: ser.JonGuiDataCameraHeat camera_heat = 4;
   */
  cameraHeat?: JonGuiDataCameraHeat | undefined;

  /**
   * @generated from field: ser.JonGuiDataRotary rotary = 5;
   */
  rotary?: JonGuiDataRotary | undefined;

  /**
   * CUDA IPC channel metadata
   *
   * @generated from field: ser.CvChannelMeta channel_day = 6;
   */
  channelDay?: CvChannelMeta | undefined;

  /**
   * @generated from field: ser.CvChannelMeta channel_heat = 7;
   */
  channelHeat?: CvChannelMeta | undefined;
};

/**
 * Describes the message ser.CvMeta.
 * Use `create(CvMetaSchema)` to create a new message.
 */
export const CvMetaSchema: GenMessage<CvMeta> = /*@__PURE__*/
  messageDesc(file_opaque_cv_meta, 1);

