// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file opaque/object_detections_heat.proto (package ser, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../buf/validate/validate_pb";
import type { DetectionConfig, DetectionFrameMeta, DetectionStatus, ObjectDetection } from "./detection_common_pb";
import { file_opaque_detection_common } from "./detection_common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file opaque/object_detections_heat.proto.
 */
export const file_opaque_object_detections_heat: GenFile = /*@__PURE__*/
  fileDesc("CiNvcGFxdWUvb2JqZWN0X2RldGVjdGlvbnNfaGVhdC5wcm90bxIDc2VyIo8CChRPYmplY3REZXRlY3Rpb25zSGVhdBIwCgZzdGF0dXMYASABKA4yFC5zZXIuRGV0ZWN0aW9uU3RhdHVzQgq6SAeCAQQQASAAEjMKCmRldGVjdGlvbnMYAiADKAsyFC5zZXIuT2JqZWN0RGV0ZWN0aW9uQgm6SAaSAQMQgAISGwoKbGF0ZW5jeV9ucxgDIAEoBEIHukgEMgIoABImCgVmcmFtZRgEIAEoCzIXLnNlci5EZXRlY3Rpb25GcmFtZU1ldGESJAoGY29uZmlnGAUgASgLMhQuc2VyLkRldGVjdGlvbkNvbmZpZxIlChRjYXB0dXJlX21vbm90b25pY191cxgGIAEoBEIHukgEMgIoAEJJWkdnaXQtY29kZWNvbW1pdC5ldS1jZW50cmFsLTEuYW1hem9uYXdzLmNvbS92MS9yZXBvcy9qZXR0aXNvbi9qb25wL29wYXF1ZWIGcHJvdG8z", [file_buf_validate_validate, file_opaque_detection_common]);

/**
 * Object detection results for HEAT camera channel.
 * Injected by cv-gateway into JonGUIState.opaque_payloads at inference rate (~30fps).
 * Errors logged to stderr, not embedded in proto.
 *
 * UUID: 019c40f6-825d-7e0e-9893-87c7b167a751
 *
 * @generated from message ser.ObjectDetectionsHeat
 */
export type ObjectDetectionsHeat = Message<"ser.ObjectDetectionsHeat"> & {
  /**
   * Inference status (required, must be valid enum value)
   *
   * @generated from field: ser.DetectionStatus status = 1;
   */
  status: DetectionStatus;

  /**
   * Detected objects (up to 256)
   *
   * @generated from field: repeated ser.ObjectDetection detections = 2;
   */
  detections: ObjectDetection[];

  /**
   * End-to-end inference latency (nanoseconds)
   *
   * @generated from field: uint64 latency_ns = 3;
   */
  latencyNs: bigint;

  /**
   * Frame metadata for correlation
   *
   * @generated from field: ser.DetectionFrameMeta frame = 4;
   */
  frame?: DetectionFrameMeta;

  /**
   * Inference configuration used
   *
   * @generated from field: ser.DetectionConfig config = 5;
   */
  config?: DetectionConfig;

  /**
   * Correlation timestamp (CLOCK_MONOTONIC, microseconds) - matches CvMeta pattern
   *
   * @generated from field: uint64 capture_monotonic_us = 6;
   */
  captureMonotonicUs: bigint;
};

/**
 * Describes the message ser.ObjectDetectionsHeat.
 * Use `create(ObjectDetectionsHeatSchema)` to create a new message.
 */
export const ObjectDetectionsHeatSchema: GenMessage<ObjectDetectionsHeat> = /*@__PURE__*/
  messageDesc(file_opaque_object_detections_heat, 0);

