// @generated by protoc-gen-es v2.13.0 with parameter "target=ts"
// @generated from file ui/ui_input.proto (package ui, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ui/ui_input.proto.
 */
export const file_ui_ui_input: GenFile = /*@__PURE__*/
  fileDesc("ChF1aS91aV9pbnB1dC5wcm90bxICdWki1gEKDFBvaW50ZXJFdmVudBIrCgVwaGFzZRgBIAEoDjIQLnVpLlBvaW50ZXJQaGFzZUIKukgHggEEEAEgABIpCgRraW5kGAIgASgOMg8udWkuUG9pbnRlcktpbmRCCrpIB4IBBBABIAASEgoKcG9pbnRlcl9pZBgDIAEoDRIiCgF4GAQgASgBQhe6SBQSEhkAAAAAAADwPykAAAAAAADwvxIiCgF5GAUgASgBQhe6SBQSEhkAAAAAAADwPykAAAAAAADwvxISCgpldmVudF90aW1lGAYgASgEIlcKCUxpZmVjeWNsZRIoCgV0aGVtZRgBIAEoDjINLnVpLlRoZW1lTW9kZUIKukgHggEEEAEgABIPCgdmb2N1c2VkGAIgASgIEg8KB3Zpc2libGUYAyABKAgiggEKCkhvc3RUb1dhc20SGwoHdmVyc2lvbhgBIAEoDUIKukgHKgUY/wEoARIjCgdwb2ludGVyGAIgASgLMhAudWkuUG9pbnRlckV2ZW50SAASIgoJbGlmZWN5Y2xlGAMgASgLMg0udWkuTGlmZWN5Y2xlSABCDgoFZXZlbnQSBbpIAggBIjYKCkhvdmVyU3RhdGUSEwoLaG92ZXJlZF91aWQYASABKA0SEwoLaW50ZXJhY3RpdmUYAiABKAgiOwoNQ3Vyc29yUmVxdWVzdBIqCgZjdXJzb3IYASABKA4yDi51aS5DdXJzb3JUeXBlQgq6SAeCAQQQASAAIoABCgpXYXNtVG9Ib3N0EhsKB3ZlcnNpb24YASABKA1CCrpIByoFGP8BKAESHwoFaG92ZXIYAiABKAsyDi51aS5Ib3ZlclN0YXRlSAASIwoGY3Vyc29yGAMgASgLMhEudWkuQ3Vyc29yUmVxdWVzdEgAQg8KBnJlcG9ydBIFukgCCAEqVwoSSW5wdXRTY2hlbWFWZXJzaW9uEiQKIElOUFVUX1NDSEVNQV9WRVJTSU9OX1VOU1BFQ0lGSUVEEAASGwoXSU5QVVRfU0NIRU1BX1ZFUlNJT05fVjEQASqNAQoMUG9pbnRlclBoYXNlEh0KGVBPSU5URVJfUEhBU0VfVU5TUEVDSUZJRUQQABIWChJQT0lOVEVSX1BIQVNFX0RPV04QARIWChJQT0lOVEVSX1BIQVNFX01PVkUQAhIUChBQT0lOVEVSX1BIQVNFX1VQEAMSGAoUUE9JTlRFUl9QSEFTRV9DQU5DRUwQBCpxCgtQb2ludGVyS2luZBIcChhQT0lOVEVSX0tJTkRfVU5TUEVDSUZJRUQQABIWChJQT0lOVEVSX0tJTkRfTU9VU0UQARIWChJQT0lOVEVSX0tJTkRfVE9VQ0gQAhIUChBQT0lOVEVSX0tJTkRfUEVOEAMqUgoJVGhlbWVNb2RlEhoKFlRIRU1FX01PREVfVU5TUEVDSUZJRUQQABIUChBUSEVNRV9NT0RFX0xJR0hUEAESEwoPVEhFTUVfTU9ERV9EQVJLEAIqvAEKCkN1cnNvclR5cGUSGwoXQ1VSU09SX1RZUEVfVU5TUEVDSUZJRUQQABIXChNDVVJTT1JfVFlQRV9ERUZBVUxUEAESFwoTQ1VSU09SX1RZUEVfUE9JTlRFUhACEhQKEENVUlNPUl9UWVBFX1RFWFQQAxIUChBDVVJTT1JfVFlQRV9HUkFCEAQSFgoSQ1VSU09SX1RZUEVfUkVTSVpFEAUSGwoXQ1VSU09SX1RZUEVfTk9UX0FMTE9XRUQQBkJFWkNnaXQtY29kZWNvbW1pdC5ldS1jZW50cmFsLTEuYW1hem9uYXdzLmNvbS92MS9yZXBvcy9qZXR0aXNvbi9qb25wL3VpYgZwcm90bzM", [file_buf_validate_validate]);

/**
 * A bounded adaptation of the W3C Pointer Events API (mouse + touch + pen
 * unified). The host forwards every pointer event; the WASM accumulates them
 * into its fixed pointer-state table by `pointer_id` and runs the gesture FSM.
 * The WASM SELF-VALIDATES at the decode boundary (nanopb strips buf.validate):
 * reject phase/kind = 0, reject event_time = 0, clamp NDC, find-slot-or-drop on
 * pointer_id, clamp non-positive FSM time deltas.
 *
 * @generated from message ui.PointerEvent
 */
export type PointerEvent = Message<"ui.PointerEvent"> & {
  /**
   * @generated from field: ui.PointerPhase phase = 1;
   */
  phase: PointerPhase;

  /**
   * @generated from field: ui.PointerKind kind = 2;
   */
  kind: PointerKind;

  /**
   * W3C pointerId — the multi-pointer FSM key (pinch keys on ≥2)
   *
   * @generated from field: uint32 pointer_id = 3;
   */
  pointerId: number;

  /**
   * NDC, +x right
   *
   * @generated from field: double x = 4;
   */
  x: number;

  /**
   * NDC, +y UP
   *
   * @generated from field: double y = 5;
   */
  y: number;

  /**
   * W3C event.timeStamp, ms — the FSM clock (EVENT time, NOT the render tick)
   *
   * @generated from field: uint64 event_time = 6;
   */
  eventTime: bigint;
};

/**
 * Describes the message ui.PointerEvent.
 * Use `create(PointerEventSchema)` to create a new message.
 */
export const PointerEventSchema: GenMessage<PointerEvent> = /*@__PURE__*/
  messageDesc(file_ui_ui_input, 0);

/**
 * OS lifecycle the host pushes for WASM restyle / pause. focused/visible = false
 * also doubles as the whole-surface FSM flush (recovers from blur/tab-switch
 * pointer loss that a per-pointer CANCEL cannot cover).
 *
 * @generated from message ui.Lifecycle
 */
export type Lifecycle = Message<"ui.Lifecycle"> & {
  /**
   * @generated from field: ui.ThemeMode theme = 1;
   */
  theme: ThemeMode;

  /**
   * @generated from field: bool focused = 2;
   */
  focused: boolean;

  /**
   * @generated from field: bool visible = 3;
   */
  visible: boolean;
};

/**
 * Describes the message ui.Lifecycle.
 * Use `create(LifecycleSchema)` to create a new message.
 */
export const LifecycleSchema: GenMessage<Lifecycle> = /*@__PURE__*/
  messageDesc(file_ui_ui_input, 1);

/**
 * Host → WASM envelope. `version` is field 1 (fail-fast guard); the consumer
 * checks it against the CURRENT value FIRST and returns a mismatch error — no
 * migration branch, no version-sniffing. {gte:1} rejects the proto3 default 0.
 *
 * @generated from message ui.HostToWasm
 */
export type HostToWasm = Message<"ui.HostToWasm"> & {
  /**
   * @generated from field: uint32 version = 1;
   */
  version: number;

  /**
   * @generated from oneof ui.HostToWasm.event
   */
  event: {
    /**
     * @generated from field: ui.PointerEvent pointer = 2;
     */
    value: PointerEvent;
    case: "pointer";
  } | {
    /**
     * @generated from field: ui.Lifecycle lifecycle = 3;
     */
    value: Lifecycle;
    case: "lifecycle";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message ui.HostToWasm.
 * Use `create(HostToWasmSchema)` to create a new message.
 */
export const HostToWasmSchema: GenMessage<HostToWasm> = /*@__PURE__*/
  messageDesc(file_ui_ui_input, 2);

/**
 * What the WASM hit-test found under the pointer. Identity travels as the
 * WidgetNode.uid (a uint32), never a name — no string, stays size-bound.
 *
 * @generated from message ui.HoverState
 */
export type HoverState = Message<"ui.HoverState"> & {
  /**
   * ui_ast WidgetNode.uid; 0 = nothing hovered
   *
   * @generated from field: uint32 hovered_uid = 1;
   */
  hoveredUid: number;

  /**
   * host shows an interactive affordance when true
   *
   * @generated from field: bool interactive = 2;
   */
  interactive: boolean;
};

/**
 * Describes the message ui.HoverState.
 * Use `create(HoverStateSchema)` to create a new message.
 */
export const HoverStateSchema: GenMessage<HoverState> = /*@__PURE__*/
  messageDesc(file_ui_ui_input, 3);

/**
 * The cursor the WASM wants the host to render.
 *
 * @generated from message ui.CursorRequest
 */
export type CursorRequest = Message<"ui.CursorRequest"> & {
  /**
   * @generated from field: ui.CursorType cursor = 1;
   */
  cursor: CursorType;
};

/**
 * Describes the message ui.CursorRequest.
 * Use `create(CursorRequestSchema)` to create a new message.
 */
export const CursorRequestSchema: GenMessage<CursorRequest> = /*@__PURE__*/
  messageDesc(file_ui_ui_input, 4);

/**
 * WASM → host envelope. Same version-guard contract as HostToWasm.
 *
 * @generated from message ui.WasmToHost
 */
export type WasmToHost = Message<"ui.WasmToHost"> & {
  /**
   * @generated from field: uint32 version = 1;
   */
  version: number;

  /**
   * @generated from oneof ui.WasmToHost.report
   */
  report: {
    /**
     * @generated from field: ui.HoverState hover = 2;
     */
    value: HoverState;
    case: "hover";
  } | {
    /**
     * @generated from field: ui.CursorRequest cursor = 3;
     */
    value: CursorRequest;
    case: "cursor";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message ui.WasmToHost.
 * Use `create(WasmToHostSchema)` to create a new message.
 */
export const WasmToHostSchema: GenMessage<WasmToHost> = /*@__PURE__*/
  messageDesc(file_ui_ui_input, 5);

/**
 * Channel schema version registry — the canonical list of valid versions. The
 * wire field is a uint32 (range-validated {gte:1,lte:255}) so it fail-fast
 * rejects the proto3 default 0; this enum documents which values are valid.
 *
 * @generated from enum ui.InputSchemaVersion
 */
export enum InputSchemaVersion {
  /**
   * @generated from enum value: INPUT_SCHEMA_VERSION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: INPUT_SCHEMA_VERSION_V1 = 1;
   */
  V1 = 1,
}

/**
 * Describes the enum ui.InputSchemaVersion.
 */
export const InputSchemaVersionSchema: GenEnum<InputSchemaVersion> = /*@__PURE__*/
  enumDesc(file_ui_ui_input, 0);

/**
 * W3C-style pointer lifecycle phase (host input device → WASM hit-test + FSM).
 * CANCEL = pointercancel / lostpointercapture (palm-reject / OS-takeover /
 * capture loss) — the FSM hard-aborts the pointer and emits NO terminal, so a
 * lost contact never fires a phantom pan-end / tap device command.
 *
 * @generated from enum ui.PointerPhase
 */
export enum PointerPhase {
  /**
   * @generated from enum value: POINTER_PHASE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: POINTER_PHASE_DOWN = 1;
   */
  DOWN = 1,

  /**
   * @generated from enum value: POINTER_PHASE_MOVE = 2;
   */
  MOVE = 2,

  /**
   * @generated from enum value: POINTER_PHASE_UP = 3;
   */
  UP = 3,

  /**
   * @generated from enum value: POINTER_PHASE_CANCEL = 4;
   */
  CANCEL = 4,
}

/**
 * Describes the enum ui.PointerPhase.
 */
export const PointerPhaseSchema: GenEnum<PointerPhase> = /*@__PURE__*/
  enumDesc(file_ui_ui_input, 1);

/**
 * Pointing-device kind (W3C pointerType), for LVGL input semantics + the
 * hit-test path (mouse can hover without contact; touch cannot).
 *
 * @generated from enum ui.PointerKind
 */
export enum PointerKind {
  /**
   * @generated from enum value: POINTER_KIND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: POINTER_KIND_MOUSE = 1;
   */
  MOUSE = 1,

  /**
   * @generated from enum value: POINTER_KIND_TOUCH = 2;
   */
  TOUCH = 2,

  /**
   * @generated from enum value: POINTER_KIND_PEN = 3;
   */
  PEN = 3,
}

/**
 * Describes the enum ui.PointerKind.
 */
export const PointerKindSchema: GenEnum<PointerKind> = /*@__PURE__*/
  enumDesc(file_ui_ui_input, 2);

/**
 * OS theme the host reports for WASM restyle.
 *
 * @generated from enum ui.ThemeMode
 */
export enum ThemeMode {
  /**
   * @generated from enum value: THEME_MODE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: THEME_MODE_LIGHT = 1;
   */
  LIGHT = 1,

  /**
   * @generated from enum value: THEME_MODE_DARK = 2;
   */
  DARK = 2,
}

/**
 * Describes the enum ui.ThemeMode.
 */
export const ThemeModeSchema: GenEnum<ThemeMode> = /*@__PURE__*/
  enumDesc(file_ui_ui_input, 3);

/**
 * Cursor the WASM requests the host render over the hovered region.
 *
 * @generated from enum ui.CursorType
 */
export enum CursorType {
  /**
   * @generated from enum value: CURSOR_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CURSOR_TYPE_DEFAULT = 1;
   */
  DEFAULT = 1,

  /**
   * @generated from enum value: CURSOR_TYPE_POINTER = 2;
   */
  POINTER = 2,

  /**
   * @generated from enum value: CURSOR_TYPE_TEXT = 3;
   */
  TEXT = 3,

  /**
   * @generated from enum value: CURSOR_TYPE_GRAB = 4;
   */
  GRAB = 4,

  /**
   * @generated from enum value: CURSOR_TYPE_RESIZE = 5;
   */
  RESIZE = 5,

  /**
   * @generated from enum value: CURSOR_TYPE_NOT_ALLOWED = 6;
   */
  NOT_ALLOWED = 6,
}

/**
 * Describes the enum ui.CursorType.
 */
export const CursorTypeSchema: GenEnum<CursorType> = /*@__PURE__*/
  enumDesc(file_ui_ui_input, 4);

