// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file ui/ui_nodes.proto (package ui, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ui/ui_nodes.proto.
 */
export const file_ui_ui_nodes: GenFile = /*@__PURE__*/
  fileDesc("ChF1aS91aV9ub2Rlcy5wcm90bxICdWkiKQoPRml4ZWRQb2ludFNjYWxlEhYKBXNjYWxlGAEgASgNQge6SAQqAigBIngKDFN0YXRlQmluZGluZxIjChBzdGF0ZV9maWVsZF9wYXRoGAEgASgJQgm6SAZyBBABGH8SHwoMc3ViamVjdF9uYW1lGAIgASgJQgm6SAZyBBABGD8SIgoFc2NhbGUYAyABKAsyEy51aS5GaXhlZFBvaW50U2NhbGUiUwoOQ29tbWFuZEJpbmRpbmcSHQoKY29tbWFuZF9pZBgBIAEoCUIJukgGcgQQARg/EiIKBXNjYWxlGAIgASgLMhMudWkuRml4ZWRQb2ludFNjYWxlIrgBCgxDbGFoZUNvbnRyb2wSGwoHdmVyc2lvbhgBIAEoDUIKukgHKgUY/wEoARIWCgV0aXRsZRgCIAEoCUIHukgEcgIYPxIfCgVzdGF0ZRgDIAEoCzIQLnVpLlN0YXRlQmluZGluZxIjCgdjb21tYW5kGAQgASgLMhIudWkuQ29tbWFuZEJpbmRpbmcSEQoJbWluX3ZhbHVlGAUgASgFEhoKCW1heF92YWx1ZRgGIAEoBUIHukgEGgIgACpUChFOb2RlU2NoZW1hVmVyc2lvbhIjCh9OT0RFX1NDSEVNQV9WRVJTSU9OX1VOU1BFQ0lGSUVEEAASGgoWTk9ERV9TQ0hFTUFfVkVSU0lPTl9WMRABQkVaQ2dpdC1jb2RlY29tbWl0LmV1LWNlbnRyYWwtMS5hbWF6b25hd3MuY29tL3YxL3JlcG9zL2pldHRpc29uL2pvbnAvdWliBnByb3RvMw", [file_buf_validate_validate]);

/**
 * How a normalized control value crosses the int-only WASM ABI. The camera
 * state/command fields are `double` ∈ [0,1] (e.g. camera_day.clahe_level),
 * but subjects + host_send_command carry only i32. `scale` is the per-mille
 * multiplier that lives WITH the binding (not a magic constant in Rust):
 *   state→subject:   (value * scale).round() as i32
 *   event→command:   int_value as f64 / scale
 * scale = 1000 for a [0,1] double; scale = 1 for an already-integer field.
 *
 * @generated from message ui.FixedPointScale
 */
export type FixedPointScale = Message<"ui.FixedPointScale"> & {
  /**
   * Per-mille (or per-unit) multiplier. Must be > 0; the projector/builder
   * divide by it, so 0 is a divide-by-zero author error.
   *
   * @generated from field: uint32 scale = 1;
   */
  scale: number;
};

/**
 * Describes the message ui.FixedPointScale.
 * Use `create(FixedPointScaleSchema)` to create a new message.
 */
export const FixedPointScaleSchema: GenMessage<FixedPointScale> = /*@__PURE__*/
  messageDesc(file_ui_ui_nodes, 0);

/**
 * The proto STATE this node displays. The lowering resolves
 * `state_field_path` against the prost `ser::` types at test time (Class-c2)
 * and the projector reads that field from JonGuiState into `subject_name`.
 *
 * @generated from message ui.StateBinding
 */
export type StateBinding = Message<"ui.StateBinding"> & {
  /**
   * Dotted JonGuiState field path, e.g. "camera_day.clahe_level". Resolves
   * structurally against the `ser` tree (state-projector input).
   *
   * @generated from field: string state_field_path = 1;
   */
  stateFieldPath: string;

  /**
   * The reactive subject this state feeds, e.g. "day_clahe". Bound into the
   * lowered Screen's SubjectDeclaration + the widget's `bindings` map.
   *
   * @generated from field: string subject_name = 2;
   */
  subjectName: string;

  /**
   * Fixed-point convention for state→subject projection (absent ⇒ scale 1).
   *
   * @generated from field: ui.FixedPointScale scale = 3;
   */
  scale?: FixedPointScale | undefined;
};

/**
 * Describes the message ui.StateBinding.
 * Use `create(StateBindingSchema)` to create a new message.
 */
export const StateBindingSchema: GenMessage<StateBinding> = /*@__PURE__*/
  messageDesc(file_ui_ui_nodes, 1);

/**
 * The proto COMMAND this node sends. `command_id` IS the EventBinding.name
 * the lowered Screen emits and the command-builder maps to a cmd.Root oneof
 * leaf (verified against the `cmd::` tree, Class-c2 / R4 oracle).
 *
 * @generated from message ui.CommandBinding
 */
export type CommandBinding = Message<"ui.CommandBinding"> & {
  /**
   * Command identifier = EventBinding.name, e.g. "day.clahe.set". Resolves
   * to a concrete cmd.Root variant (command-builder input).
   *
   * @generated from field: string command_id = 1;
   */
  commandId: string;

  /**
   * Fixed-point convention for event→command projection (absent ⇒ scale 1).
   *
   * @generated from field: ui.FixedPointScale scale = 2;
   */
  scale?: FixedPointScale | undefined;
};

/**
 * Describes the message ui.CommandBinding.
 * Use `create(CommandBindingSchema)` to create a new message.
 */
export const CommandBindingSchema: GenMessage<CommandBinding> = /*@__PURE__*/
  messageDesc(file_ui_ui_nodes, 2);

/**
 * The L3 ClaheControl node — day-camera CLAHE level: a labelled card holding
 * a slider that DISPLAYS camera_day.clahe_level and SENDS SetClaheLevel. The
 * proven Phase-1 slice; the per-node shape every L3 node generalizes to.
 *
 * @generated from message ui.ClaheControl
 */
export type ClaheControl = Message<"ui.ClaheControl"> & {
  /**
   * Schema version — checked FIRST by the lowering (fail-fast guard). A node
   * whose version != the current NodeSchemaVersion is rejected with
   * Err(SchemaMismatch); {gte: 1} rejects the unset/0 default.
   *
   * @generated from field: uint32 version = 1;
   */
  version: number;

  /**
   * Card title shown above the slider (lowered to a Label atom).
   *
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * State display binding: camera_day.clahe_level → "day_clahe" subject,
   * scale 1000 (double[0,1] → per-mille int).
   *
   * @generated from field: ui.StateBinding state = 3;
   */
  state?: StateBinding | undefined;

  /**
   * Command binding: slider value-changed → "day.clahe.set" → SetClaheLevel,
   * scale 1000 (per-mille int → double[0,1]).
   *
   * @generated from field: ui.CommandBinding command = 4;
   */
  command?: CommandBinding | undefined;

  /**
   * Slider integer range AFTER scaling (e.g. 0..1000 for a [0,1] double at
   * scale 1000). These become the lowered SliderProps.min_value/max_value.
   *
   * @generated from field: int32 min_value = 5;
   */
  minValue: number;

  /**
   * @generated from field: int32 max_value = 6;
   */
  maxValue: number;
};

/**
 * Describes the message ui.ClaheControl.
 * Use `create(ClaheControlSchema)` to create a new message.
 */
export const ClaheControlSchema: GenMessage<ClaheControl> = /*@__PURE__*/
  messageDesc(file_ui_ui_nodes, 3);

/**
 * Node-schema version constant. The lowering entry-point checks the wire
 * `version` field against the CURRENT value FIRST and returns
 * Err(SchemaMismatch) on any mismatch — fail-fast, no migration branch, no
 * version-sniffing. protogen + bindings + lowering regenerate in lockstep,
 * so a mismatch can only mean a stale fixture (a bug). Start at 1 (0 is the
 * proto3 default / "unset", deliberately invalid so an un-versioned node is
 * rejected by the {gte: 1} guard on the field).
 *
 * @generated from enum ui.NodeSchemaVersion
 */
export enum NodeSchemaVersion {
  /**
   * @generated from enum value: NODE_SCHEMA_VERSION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: NODE_SCHEMA_VERSION_V1 = 1;
   */
  V1 = 1,
}

/**
 * Describes the enum ui.NodeSchemaVersion.
 */
export const NodeSchemaVersionSchema: GenEnum<NodeSchemaVersion> = /*@__PURE__*/
  enumDesc(file_ui_ui_nodes, 0);

